import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop11widget2/generated/GeneratedGroup28Widget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop11widget2/generated/GeneratedRectangle219Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop11widget2/generated/GeneratediconmessagecircleWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop11widget2/generated/GeneratediconshoppingcartWidget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop11widget2/generated/GeneratedArrowright113Widget63.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop11widget2/generated/GeneratedRectangle218Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop11widget2/generated/GeneratedLetstakeyourjerseyhomeWidget30.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop11widget2/generated/GeneratedBuynowWidget17.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop11widget2/generated/GeneratedRectangle220Widget9.dart';

/* Frame Desktop - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop11Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1254.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 1849.0,
                              top: 230.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 1024.0,
                              child: GeneratedArrowright113Widget63(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1005.0,
                              height: 738.6837158203125,
                              child: GeneratedGroup28Widget10(),
                            ),
                            Positioned(
                              left: 934.0,
                              top: 892.0,
                              right: null,
                              bottom: null,
                              width: 506.0,
                              height: 132.0,
                              child: GeneratedRectangle219Widget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.10972222222222222;

                                final double height =
                                    constraints.maxHeight * 0.154296875;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.7375,
                                      y: constraints.maxHeight * 0.853515625,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratediconshoppingcartWidget6(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 1220.0,
                              top: 895.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 125.0,
                              child: GeneratedRectangle220Widget9(),
                            ),
                            Positioned(
                              left: 1242.0,
                              top: 915.0,
                              right: null,
                              bottom: null,
                              width: 177.5,
                              height: 67.45265197753906,
                              child: GeneratedBuynowWidget17(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.09166666666666666;

                                final double height =
                                    constraints.maxHeight * 0.12890625;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.6520833333333333,
                                      y: constraints.maxHeight * 0.8671875,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratediconmessagecircleWidget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 892.0,
                              right: null,
                              bottom: null,
                              width: 934.0,
                              height: 132.0,
                              child: GeneratedRectangle218Widget6(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 931.0,
                              right: null,
                              bottom: null,
                              width: 914.75,
                              height: 154.24070739746094,
                              child: GeneratedLetstakeyourjerseyhomeWidget30(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
