import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop6widget1/generated/GeneratedGroup20Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop6widget1/generated/GeneratedKonfirmasiWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop6widget1/generated/GeneratedRectangle164Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop6widget1/generated/GeneratedRectangle168Widget.dart';

/* Frame Desktop - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop6Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 1024.0,
                              child: GeneratedGroup20Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -8.0,
                              right: null,
                              bottom: null,
                              width: 267.0,
                              height: 201.0,
                              child: GeneratedRectangle164Widget(),
                            ),
                            Positioned(
                              left: 1141.0,
                              top: 943.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 81.0,
                              child: GeneratedRectangle168Widget(),
                            ),
                            Positioned(
                              left: 1120.0,
                              top: 927.0,
                              right: null,
                              bottom: null,
                              width: 337.0,
                              height: 96.0,
                              child: GeneratedKonfirmasiWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
