import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox24widget2/generated/GeneratediconarrowbackoutlineWidget39.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox24widget2/generated/GeneratedGroup27Widget16.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox24widget2/generated/GeneratedJUVENTUSWidget20.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox24widget2/generated/GeneratedThisJuventusjerseyhasanelegantblackandwhitedominanceWid.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox24widget2/generated/GeneratedMybasketWidget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox24widget2/generated/GeneratedRp155000Widget23.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox24widget2/generated/GeneratedRectangle196Widget29.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox24widget2/generated/GeneratedBuynowWidget40.dart';

/* Frame iPhone 11 Pro / X - 24
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX24Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 93.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 82.0,
                child: GeneratedMybasketWidget6(),
              ),
              Positioned(
                left: 12.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 100.0,
                child: GeneratedGroup27Widget16(),
              ),
              Positioned(
                left: 119.0,
                top: 165.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 31.0,
                child: GeneratedJUVENTUSWidget20(),
              ),
              Positioned(
                left: 119.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 50.0,
                child:
                    GeneratedThisJuventusjerseyhasanelegantblackandwhitedominanceWid(),
              ),
              Positioned(
                left: 251.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 14.0,
                child: GeneratedRp155000Widget23(),
              ),
              Positioned(
                left: 267.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 49.0,
                child: GeneratedRectangle196Widget29(),
              ),
              Positioned(
                left: 267.0,
                top: 768.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 57.0,
                child: GeneratedBuynowWidget40(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget39(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
