import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox28widget2/generated/GeneratedGroup55Widget2.dart';

/* Frame iPhone 11 Pro / X - 28
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX28Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 194.0,
                child: GeneratedGroup55Widget2(),
              )
            ]),
      ),
    ));
  }
}
