import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedLine50Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedRectangle149Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedLine54Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedLine51Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedLine47Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedRectangle150Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedKonfirmasiWidget12.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedRectangle152Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedRectangle146Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedLine49Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedLine53Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedRectangle77Widget36.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedLine52Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedTennisball1Widget36.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedRectangle148Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedGroup16Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedArrowright113Widget50.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedMasukkanKodeWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedLine48Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget36/generated/GeneratedRectangle154Widget4.dart';

/* Frame IMINN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIMINNWidget36 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1497.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 1080.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 690.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedTennisball1Widget36(),
                            ),
                            Positioned(
                              left: 1849.0,
                              top: 174.0,
                              right: null,
                              bottom: null,
                              width: 13.0,
                              height: 13.0,
                              child: GeneratedArrowright113Widget50(),
                            ),
                            Positioned(
                              left: 669.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 283.0,
                              child: GeneratedRectangle77Widget36(),
                            ),
                            Positioned(
                              left: 331.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 1330.0,
                              height: 742.0,
                              child: GeneratedRectangle146Widget5(),
                            ),
                            Positioned(
                              left: 622.0,
                              top: 468.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 145.0,
                              child: GeneratedGroup16Widget6(),
                            ),
                            Positioned(
                              left: 822.0,
                              top: 468.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 147.0,
                              child: GeneratedRectangle148Widget5(),
                            ),
                            Positioned(
                              left: 1022.0,
                              top: 468.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 147.0,
                              child: GeneratedRectangle149Widget4(),
                            ),
                            Positioned(
                              left: 1222.0,
                              top: 468.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 147.0,
                              child: GeneratedRectangle150Widget5(),
                            ),
                            Positioned(
                              left: 621.0,
                              top: 467.0,
                              right: null,
                              bottom: null,
                              width: 206.4751739501953,
                              height: 1.0,
                              child: GeneratedLine47Widget5(),
                            ),
                            Positioned(
                              left: 767.0,
                              top: 467.0,
                              right: null,
                              bottom: null,
                              width: 205.769287109375,
                              height: 1.0,
                              child: GeneratedLine48Widget4(),
                            ),
                            Positioned(
                              left: 822.0,
                              top: 470.0,
                              right: null,
                              bottom: null,
                              width: 203.65167236328125,
                              height: 1.0,
                              child: GeneratedLine49Widget5(),
                            ),
                            Positioned(
                              left: 967.0,
                              top: 467.0,
                              right: null,
                              bottom: null,
                              width: 205.769287109375,
                              height: 1.0,
                              child: GeneratedLine50Widget5(),
                            ),
                            Positioned(
                              left: 1023.0,
                              top: 467.0,
                              right: null,
                              bottom: null,
                              width: 205.0658416748047,
                              height: 1.0,
                              child: GeneratedLine51Widget5(),
                            ),
                            Positioned(
                              left: 1165.0,
                              top: 468.0,
                              right: null,
                              bottom: null,
                              width: 202.9507293701172,
                              height: 1.0,
                              child: GeneratedLine52Widget5(),
                            ),
                            Positioned(
                              left: 1221.0,
                              top: 468.0,
                              right: null,
                              bottom: null,
                              width: 205.769287109375,
                              height: 1.0,
                              child: GeneratedLine53Widget4(),
                            ),
                            Positioned(
                              left: 1367.0,
                              top: 468.0,
                              right: null,
                              bottom: null,
                              width: 205.06097412109375,
                              height: 1.0,
                              child: GeneratedLine54Widget4(),
                            ),
                            Positioned(
                              left: 667.0,
                              top: 664.0,
                              right: null,
                              bottom: null,
                              width: 659.0,
                              height: 135.0,
                              child: GeneratedRectangle152Widget5(),
                            ),
                            Positioned(
                              left: 331.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 1335.0,
                              height: 829.0,
                              child: GeneratedKonfirmasiWidget12(),
                            ),
                            Positioned(
                              left: 691.0,
                              top: 234.0,
                              right: null,
                              bottom: null,
                              width: 611.0,
                              height: 135.0,
                              child: GeneratedRectangle154Widget4(),
                            ),
                            Positioned(
                              left: 680.0,
                              top: 227.0,
                              right: null,
                              bottom: null,
                              width: 612.0,
                              height: 144.0,
                              child: GeneratedMasukkanKodeWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
