import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedRectangle162Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedUbahWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratediconarrowbackoutlineWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedRectangle157Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedWidget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedRectangle159Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedWidget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedNamaWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedRectangle158Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedAlamatWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedLine7Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedUbahProfilWidget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedJenisKelaminWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedRectangle161Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedKonfirmasiWidget14.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedWidget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox12widget1/generated/GeneratedRectangle160Widget7.dart';

/* Frame iPhone 11 Pro / X - 12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX12Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 213.0,
                child: GeneratedRectangle157Widget3(),
              ),
              Positioned(
                left: 77.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 78.0,
                child: GeneratedUbahProfilWidget6(),
              ),
              Positioned(
                left: 160.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: GeneratedRectangle158Widget7(),
              ),
              Positioned(
                left: 170.0,
                top: 191.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 15.0,
                child: GeneratedUbahWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 52.0,
                child: GeneratedRectangle159Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 50.0,
                child: GeneratedRectangle160Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine7Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 54.0,
                child: GeneratedNamaWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 51.0,
                child: GeneratedJenisKelaminWidget4(),
              ),
              Positioned(
                left: 263.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 55.0,
                child: GeneratedWidget9(),
              ),
              Positioned(
                left: 263.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 55.0,
                child: GeneratedWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 52.0,
                child: GeneratedRectangle161Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 54.0,
                child: GeneratedAlamatWidget4(),
              ),
              Positioned(
                left: 263.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 55.0,
                child: GeneratedWidget11(),
              ),
              Positioned(
                left: 223.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 73.0,
                child: GeneratedRectangle162Widget5(),
              ),
              Positioned(
                left: 222.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 80.0,
                child: GeneratedKonfirmasiWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.010666666666666666,
                        y: constraints.maxHeight * -0.008620689655172414,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget3(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
