description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^1.0.5"
  path_drawing: "^1.0.0"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-italic.ttf"
          style: "italic"
          weight: 400
        - 
          asset: "fonts/Roboto-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 800
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Roboto-700italic.ttf"
          style: "italic"
          weight: 700
        - 
          asset: "fonts/Roboto-italic.ttf"
          style: "italic"
          weight: 600
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Inter-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "italic"
          weight: 400
        - 
          asset: "fonts/Inter-600.ttf"
          style: "italic"
          weight: 600
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Inter-800.ttf"
          style: "normal"
          weight: 800
        - 
          asset: "fonts/Inter-500.ttf"
          style: "italic"
          weight: 500
        - 
          asset: "fonts/Inter-700.ttf"
          style: "italic"
          weight: 700
  uses-material-design: true
