import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediconcameraoutlinewidget/generated/GeneratedGroupWidget147.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediconcameraoutlinewidget/generated/GeneratedVectorWidget361.dart';

/* Group 🦆 icon "camera outline"
    Autogenerated by FlutLab FTF Generator
  */
class GeneratediconcameraoutlineWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 74.0,
      height: 67.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 1.0;
                double scaleX = (constraints.maxWidth * percentWidth) / 74.0;

                double percentHeight = 1.0;
                double scaleY = (constraints.maxHeight * percentHeight) / 67.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: 0,
                      translateY: 0,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget361())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8333333505166544;

                final double height =
                    constraints.maxHeight * 0.7500000569357801;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.08108108108108109,
                      y: constraints.maxHeight * 0.11940298507462686,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedGroupWidget147(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
