import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup41widget18/generated/GeneratedRectangle167Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup41widget18/generated/GeneratedGroup19Widget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup41widget18/generated/GeneratedLine57Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup41widget18/generated/GeneratedRectangle166Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup41widget18/generated/GeneratedKonfirmasiWidget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup41widget18/generated/GeneratedUbahProfilWidget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup41widget18/generated/GeneratedRectangle165Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup41widget18/generated/GeneratedLine58Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup41widget18/generated/GeneratedLine60Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup41widget18/generated/GeneratedRectangle164Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup41widget18/generated/GeneratedLine59Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup41widget18/generated/GeneratedRectangle168Widget6.dart';

/* Group Group 41
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup41Widget18 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1089.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 1920.0,
                    height: 1089.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0.0),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 1920.0,
                            height: 1080.0,
                            child: GeneratedGroup19Widget9(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 267.0,
                            height: 201.0,
                            child: GeneratedRectangle164Widget6(),
                          ),
                          Positioned(
                            left: 265.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 331.4000549316406,
                            height: 1.0,
                            child: GeneratedLine57Widget1(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 331.4000549316406,
                            height: 1.0,
                            child: GeneratedLine58Widget1(),
                          ),
                          Positioned(
                            left: 358.0,
                            top: 19.0,
                            right: null,
                            bottom: null,
                            width: 639.0,
                            height: 164.0,
                            child: GeneratedRectangle165Widget5(),
                          ),
                          Positioned(
                            left: 829.0,
                            top: 216.0,
                            right: null,
                            bottom: null,
                            width: 263.0,
                            height: 257.0,
                            child: GeneratedRectangle166Widget5(),
                          ),
                          Positioned(
                            left: 829.0,
                            top: 216.0,
                            right: null,
                            bottom: null,
                            width: 364.8917541503906,
                            height: 1.0,
                            child: GeneratedLine59Widget1(),
                          ),
                          Positioned(
                            left: 1090.0,
                            top: 216.0,
                            right: null,
                            bottom: null,
                            width: 364.89178466796875,
                            height: 1.0,
                            child: GeneratedLine60Widget1(),
                          ),
                          Positioned(
                            left: 867.0,
                            top: 490.0,
                            right: null,
                            bottom: null,
                            width: 186.0,
                            height: 59.0,
                            child: GeneratedRectangle167Widget5(),
                          ),
                          Positioned(
                            left: 358.0,
                            top: 19.0,
                            right: null,
                            bottom: null,
                            width: 628.0,
                            height: 166.0,
                            child: GeneratedUbahProfilWidget5(),
                          ),
                          Positioned(
                            left: 1588.0,
                            top: 987.0,
                            right: null,
                            bottom: null,
                            width: 332.0,
                            height: 102.0,
                            child: GeneratedRectangle168Widget6(),
                          ),
                          Positioned(
                            left: 1588.0,
                            top: 989.0,
                            right: null,
                            bottom: null,
                            width: 337.0,
                            height: 96.0,
                            child: GeneratedKonfirmasiWidget13(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
