import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox25widget3/generated/GeneratedGroup58Widget3.dart';

/* Frame iPhone 11 Pro / X - 25
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX25Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 28.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 791.0,
                child: GeneratedGroup58Widget3(),
              )
            ]),
      ),
    ));
  }
}
