import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox35widget1/generated/GeneratedUntitled11Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox35widget1/generated/GeneratedRectangle226Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox35widget1/generated/GeneratediconarrowbackoutlineWidget24.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox35widget1/generated/GeneratedLogoutWidget14.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox35widget1/generated/GeneratedGroup21Widget20.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox35widget1/generated/GeneratedGroup13Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox35widget1/generated/GeneratedRectangle225Widget12.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox35widget1/generated/GeneratedGroup10Widget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox35widget1/generated/GeneratedEditProfilWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox35widget1/generated/GeneratedGroup12Widget35.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox35widget1/generated/GeneratedLetstakeyourjerseyhomeWidget44.dart';

/* Frame iPhone 11 Pro / X - 35
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX35Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 402.2053527832031,
                height: 120.96703338623047,
                child: GeneratedGroup21Widget20(),
              ),
              Positioned(
                left: 18.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 386.2053527832031,
                height: 40.0,
                child: GeneratedLetstakeyourjerseyhomeWidget44(),
              ),
              Positioned(
                left: 31.0,
                top: 179.73095703125,
                right: null,
                bottom: null,
                width: 118.49947357177734,
                height: 309.0075988769531,
                child: GeneratedUntitled11Widget3(),
              ),
              Positioned(
                left: 15.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 200.0,
                child: GeneratedGroup10Widget9(),
              ),
              Positioned(
                left: 190.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 198.0,
                child: GeneratedGroup12Widget35(),
              ),
              Positioned(
                left: 174.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 216.0,
                child: GeneratedGroup13Widget8(),
              ),
              Positioned(
                left: 311.0,
                top: 4.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 24.0,
                child: GeneratedRectangle225Widget12(),
              ),
              Positioned(
                left: 311.0,
                top: 7.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 25.0,
                child: GeneratedLogoutWidget14(),
              ),
              Positioned(
                left: 70.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 24.0,
                child: GeneratedRectangle226Widget5(),
              ),
              Positioned(
                left: 75.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 17.0,
                child: GeneratedEditProfilWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.024,
                        y: constraints.maxHeight * -0.012315270935960592,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget24(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
