import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox30widget2/generated/GeneratedGroup43Widget8.dart';

/* Frame iPhone 11 Pro / X - 30
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX30Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 10.0,
                top: -16.0,
                right: null,
                bottom: null,
                width: 419.0,
                height: 715.0,
                child: GeneratedGroup43Widget8(),
              )
            ]),
      ),
    ));
  }
}
