import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop31widget2/generated/GeneratedRectangle136Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop31widget2/generated/GeneratedLogoutWidget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop31widget2/generated/GeneratedCongratulationsyourpaymenthasbeensuccessfulWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop31widget2/generated/GeneratedOkeWidget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop31widget2/generated/GeneratedEllipse9Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop31widget2/generated/GeneratedArrowright113Widget75.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop31widget2/generated/GeneratedRectangle137Widget17.dart';

/* Frame Desktop - 31
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop31Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1053.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 1375.34228515625,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 11.251853942871094,
                              height: 13.0,
                              child: GeneratedArrowright113Widget75(),
                            ),
                            Positioned(
                              left: 178.064453125,
                              top: 147.0,
                              right: null,
                              bottom: null,
                              width: 1085.64013671875,
                              height: 202.0,
                              child:
                                  GeneratedCongratulationsyourpaymenthasbeensuccessfulWidget(),
                            ),
                            Positioned(
                              left: 560.105712890625,
                              top: 347.0,
                              right: null,
                              bottom: null,
                              width: 304.66558837890625,
                              height: 328.0,
                              child: GeneratedEllipse9Widget4(),
                            ),
                            Positioned(
                              left: 560.03564453125,
                              top: 711.0,
                              right: null,
                              bottom: null,
                              width: 316.97808837890625,
                              height: 110.58885955810547,
                              child: GeneratedRectangle136Widget6(),
                            ),
                            Positioned(
                              left: 511.04443359375,
                              top: 733.0,
                              right: null,
                              bottom: null,
                              width: 407.47015380859375,
                              height: 143.0,
                              child: GeneratedOkeWidget13(),
                            ),
                            Positioned(
                              left: 1171.0428466796875,
                              top: 891.0,
                              right: null,
                              bottom: null,
                              width: 269.1789855957031,
                              height: 133.0,
                              child: GeneratedRectangle137Widget17(),
                            ),
                            Positioned(
                              left: 1171.043212890625,
                              top: 917.0,
                              right: null,
                              bottom: null,
                              width: 274.6410827636719,
                              height: 136.0,
                              child: GeneratedLogoutWidget8(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
