import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox38widget1/generated/GeneratedSeeyouWidget6.dart';

/* Frame iPhone 11 Pro / X - 38
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX38Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 51.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 106.0,
                child: GeneratedSeeyouWidget6(),
              )
            ]),
      ),
    ));
  }
}
