import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop42widget/generated/GeneratedAreyousureyouareloggedoutasaguestWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop42widget/generated/GeneratedGroup64Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop42widget/generated/GeneratedGroup65Widget.dart';

/* Frame Desktop - 42
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop42Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 242.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 957.0,
                              height: 246.0,
                              child:
                                  GeneratedAreyousureyouareloggedoutasaguestWidget(),
                            ),
                            Positioned(
                              left: 385.0,
                              top: 529.0,
                              right: null,
                              bottom: null,
                              width: 307.0,
                              height: 142.0,
                              child: GeneratedGroup65Widget(),
                            ),
                            Positioned(
                              left: 743.0,
                              top: 529.0,
                              right: null,
                              bottom: null,
                              width: 307.0,
                              height: 135.0,
                              child: GeneratedGroup64Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
