import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox4widget/generated/GeneratedRectangle226Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox4widget/generated/GeneratedEditProfilWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox4widget/generated/GeneratedGroup21Widget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox4widget/generated/GeneratedRectangle225Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox4widget/generated/GeneratedLetstakeyourjerseyhomeWidget24.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox4widget/generated/GeneratedUntitled11Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox4widget/generated/GeneratedGroup13Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox4widget/generated/GeneratedLogoutWidget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox4widget/generated/GeneratedGroup12Widget22.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox4widget/generated/GeneratedGroup10Widget4.dart';

/* Frame iPhone 11 Pro / X - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 402.2053527832031,
                height: 120.96703338623047,
                child: GeneratedGroup21Widget15(),
              ),
              Positioned(
                left: 18.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 386.2053527832031,
                height: 40.0,
                child: GeneratedLetstakeyourjerseyhomeWidget24(),
              ),
              Positioned(
                left: 31.0,
                top: 179.73095703125,
                right: null,
                bottom: null,
                width: 118.49947357177734,
                height: 309.0075988769531,
                child: GeneratedUntitled11Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 200.0,
                child: GeneratedGroup10Widget4(),
              ),
              Positioned(
                left: 190.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 198.0,
                child: GeneratedGroup12Widget22(),
              ),
              Positioned(
                left: 174.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 216.0,
                child: GeneratedGroup13Widget4(),
              ),
              Positioned(
                left: 306.0,
                top: 4.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 26.0,
                child: GeneratedRectangle225Widget8(),
              ),
              Positioned(
                left: 309.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 25.0,
                child: GeneratedLogoutWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 2.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 28.0,
                child: GeneratedRectangle226Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 17.0,
                child: GeneratedEditProfilWidget(),
              )
            ]),
      ),
    ));
  }
}
