import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop18widget2/generated/GeneratedGroup35Widget2.dart';

/* Frame Desktop - 18
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop18Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -74.0,
                              top: -50.0,
                              right: null,
                              bottom: null,
                              width: 1514.2054443359375,
                              height: 1074.0,
                              child: GeneratedGroup35Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
