import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedRectangle109Widget19.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedRectangle92Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedRectangle110Widget14.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedLine17Widget16.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedLine3Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedLanjutkandengangoogleWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedRectangle108Widget17.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedEllipse1Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedRegisterWidget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedGuestWidget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedLine2Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedRectangle107Widget16.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedLoginWidget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedLine16Widget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedDesaintanpajudul1Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedGroup7Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedLine21Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedRectangle97Widget18.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedGroup6Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedRectangle92Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedLine23Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedLine20Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedmedicalwidget1/generated/GeneratedLine22Widget1.dart';

/* Frame Medical
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMedicalWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1080.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 1920.0,
                    height: 1080.0,
                    decoration: BoxDecoration(
                      gradient: RadialGradient(
                        center:
                            Alignment(0.0552083490476063, 0.19444440908165728),
                        stops: [0.0],
                        colors: [Color.fromARGB(255, 255, 255, 255)],
                      ),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 1334.0,
                            top: 433.0,
                            right: null,
                            bottom: null,
                            width: 446.0,
                            height: 418.0,
                            child: GeneratedEllipse1Widget2(),
                          ),
                          Positioned(
                            left: 729.0,
                            top: 616.0,
                            right: null,
                            bottom: null,
                            width: 231.0,
                            height: 92.0,
                            child: GeneratedRectangle92Widget7(),
                          ),
                          Positioned(
                            left: 802.0,
                            top: 211.0,
                            right: null,
                            bottom: null,
                            width: 15.0,
                            height: 3.0,
                            child: GeneratedDesaintanpajudul1Widget3(),
                          ),
                          Positioned(
                            left: 620.0003662109375,
                            top: 493.34033203125,
                            right: null,
                            bottom: null,
                            width: 468.49676513671875,
                            height: 2.3192970752716064,
                            child: GeneratedLine2Widget6(),
                          ),
                          Positioned(
                            left: 619.9866333007812,
                            top: 564.5,
                            right: null,
                            bottom: null,
                            width: 468.0267028808594,
                            height: 1.0,
                            child: GeneratedLine3Widget6(),
                          ),
                          Positioned(
                            left: 1634.0,
                            top: 11.0,
                            right: null,
                            bottom: null,
                            width: 231.0,
                            height: 92.0,
                            child: GeneratedRectangle92Widget8(),
                          ),
                          Positioned(
                            left: 1387.0,
                            top: 11.0,
                            right: null,
                            bottom: null,
                            width: 231.0,
                            height: 92.0,
                            child: GeneratedRectangle97Widget18(),
                          ),
                          Positioned(
                            left: 718.0,
                            top: 86.0,
                            right: null,
                            bottom: null,
                            width: 261.0,
                            height: 283.0,
                            child: GeneratedRectangle107Widget16(),
                          ),
                          Positioned(
                            left: 718.0,
                            top: 87.0,
                            right: null,
                            bottom: null,
                            width: 384.24603271484375,
                            height: 1.0,
                            child: GeneratedLine16Widget10(),
                          ),
                          Positioned(
                            left: 979.0,
                            top: 87.0,
                            right: null,
                            bottom: null,
                            width: 384.2460021972656,
                            height: 1.0,
                            child: GeneratedLine17Widget16(),
                          ),
                          Positioned(
                            left: 56.0,
                            top: 397.0,
                            right: null,
                            bottom: null,
                            width: 389.0,
                            height: 323.0,
                            child: GeneratedRectangle108Widget17(),
                          ),
                          Positioned(
                            left: 534.0,
                            top: 445.0,
                            right: null,
                            bottom: null,
                            width: 73.0,
                            height: 53.0,
                            child: GeneratedRectangle109Widget19(),
                          ),
                          Positioned(
                            left: 534.0,
                            top: 515.0,
                            right: null,
                            bottom: null,
                            width: 73.0,
                            height: 53.0,
                            child: GeneratedRectangle110Widget14(),
                          ),
                          Positioned(
                            left: 646.0,
                            top: 745.0,
                            right: null,
                            bottom: null,
                            width: 395.07305908203125,
                            height: 37.0,
                            child: GeneratedGroup7Widget4(),
                          ),
                          Positioned(
                            left: 534.0,
                            top: 445.0,
                            right: null,
                            bottom: null,
                            width: 90.21086120605469,
                            height: 1.0,
                            child: GeneratedLine20Widget7(),
                          ),
                          Positioned(
                            left: 607.0,
                            top: 446.0,
                            right: null,
                            bottom: null,
                            width: 89.62700653076172,
                            height: 1.0,
                            child: GeneratedLine21Widget1(),
                          ),
                          Positioned(
                            left: 534.0,
                            top: 515.0,
                            right: null,
                            bottom: null,
                            width: 90.21086120605469,
                            height: 1.0,
                            child: GeneratedLine22Widget1(),
                          ),
                          Positioned(
                            left: 607.0,
                            top: 515.0,
                            right: null,
                            bottom: null,
                            width: 90.21086120605469,
                            height: 1.0,
                            child: GeneratedLine23Widget1(),
                          ),
                          Positioned(
                            left: 555.0,
                            top: 798.0,
                            right: null,
                            bottom: null,
                            width: 579.0,
                            height: 62.000003814697266,
                            child: GeneratedGroup6Widget3(),
                          ),
                          Positioned(
                            left: 1494.0,
                            top: 515.0,
                            right: null,
                            bottom: null,
                            width: 125.0,
                            height: 117.0,
                            child: GeneratedGroup2Widget1(),
                          ),
                          Positioned(
                            left: 731.0,
                            top: 621.0,
                            right: null,
                            bottom: null,
                            width: 230.0,
                            height: 92.0,
                            child: GeneratedLoginWidget7(),
                          ),
                          Positioned(
                            left: 1395.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 212.0,
                            height: 108.0,
                            child: GeneratedGuestWidget5(),
                          ),
                          Positioned(
                            left: 1649.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 204.0,
                            height: 108.0,
                            child: GeneratedRegisterWidget9(),
                          ),
                          Positioned(
                            left: 656.0,
                            top: 804.0,
                            right: null,
                            bottom: null,
                            width: 480.0,
                            height: 58.0,
                            child: GeneratedLanjutkandengangoogleWidget2(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
