import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup37widget1/generated/GeneratedRectangle214Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup37widget1/generated/GeneratedPPilihFotoWidget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup37widget1/generated/GeneratedRectangle211Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup37widget1/generated/GeneratedRectangle210Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup37widget1/generated/GeneratedRectangle201Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup37widget1/generated/GeneratedRectangle215Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup37widget1/generated/GeneratedRectangle212Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup37widget1/generated/GeneratedGroup32Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup37widget1/generated/GeneratedRectangle209Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup37widget1/generated/GeneratedRectangle213Widget3.dart';

/* Group Group 37
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup37Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1080.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 1920.0,
                    height: 1080.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 1920.0,
                            height: 1080.0,
                            child: GeneratedGroup32Widget5(),
                          ),
                          Positioned(
                            left: 326.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 1025.0,
                            height: 201.0,
                            child: GeneratedPPilihFotoWidget1(),
                          ),
                          Positioned(
                            left: 6.0,
                            top: 199.0,
                            right: null,
                            bottom: null,
                            width: 481.0,
                            height: 402.0,
                            child: GeneratedRectangle201Widget6(),
                          ),
                          Positioned(
                            left: 6.0,
                            top: 599.0,
                            right: null,
                            bottom: null,
                            width: 481.0,
                            height: 402.0,
                            child: GeneratedRectangle212Widget3(),
                          ),
                          Positioned(
                            left: 485.0,
                            top: 599.0,
                            right: null,
                            bottom: null,
                            width: 481.0,
                            height: 402.0,
                            child: GeneratedRectangle213Widget3(),
                          ),
                          Positioned(
                            left: 964.0,
                            top: 599.0,
                            right: null,
                            bottom: null,
                            width: 473.0,
                            height: 402.0,
                            child: GeneratedRectangle214Widget3(),
                          ),
                          Positioned(
                            left: 1435.0,
                            top: 599.0,
                            right: null,
                            bottom: null,
                            width: 481.0,
                            height: 402.0,
                            child: GeneratedRectangle215Widget3(),
                          ),
                          Positioned(
                            left: 485.0,
                            top: 199.0,
                            right: null,
                            bottom: null,
                            width: 481.0,
                            height: 402.0,
                            child: GeneratedRectangle209Widget3(),
                          ),
                          Positioned(
                            left: 964.0,
                            top: 199.0,
                            right: null,
                            bottom: null,
                            width: 481.0,
                            height: 402.0,
                            child: GeneratedRectangle210Widget3(),
                          ),
                          Positioned(
                            left: 1435.0,
                            top: 199.0,
                            right: null,
                            bottom: null,
                            width: 487.0,
                            height: 402.0,
                            child: GeneratedRectangle211Widget3(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
