import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget31/generated/GeneratedTennisball1Widget31.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget31/generated/GeneratedRectangle140Widget20.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget31/generated/GeneratedArrowright113Widget45.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget31/generated/GeneratedKeranjangSayaWidget16.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget31/generated/GeneratedGroup14Widget19.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget31/generated/GeneratedLine44Widget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget31/generated/GeneratedRectangle153Widget23.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget31/generated/GeneratedBeliSekarangWidget38.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget31/generated/GeneratedRectangle77Widget31.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget31/generated/GeneratedLine43Widget10.dart';

/* Frame IMINN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIMINNWidget31 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1080.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 1080.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 690.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedTennisball1Widget31(),
                            ),
                            Positioned(
                              left: 1849.0,
                              top: 174.0,
                              right: null,
                              bottom: null,
                              width: 13.0,
                              height: 13.0,
                              child: GeneratedArrowright113Widget45(),
                            ),
                            Positioned(
                              left: 669.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 283.0,
                              child: GeneratedRectangle77Widget31(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 55.0,
                              right: null,
                              bottom: null,
                              width: 238.0,
                              height: 238.0,
                              child: GeneratedRectangle140Widget20(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 335.1716003417969,
                              height: 1.0,
                              child: GeneratedLine43Widget10(),
                            ),
                            Positioned(
                              left: 300.0,
                              top: 61.0,
                              right: null,
                              bottom: null,
                              width: 326.6864013671875,
                              height: 1.0,
                              child: GeneratedLine44Widget10(),
                            ),
                            Positioned(
                              left: 362.0,
                              top: 127.0,
                              right: null,
                              bottom: null,
                              width: 665.0,
                              height: 168.0,
                              child: GeneratedKeranjangSayaWidget16(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 345.0,
                              right: null,
                              bottom: null,
                              width: 1759.0,
                              height: 240.0,
                              child: GeneratedGroup14Widget19(),
                            ),
                            Positioned(
                              left: 1578.0,
                              top: 934.0,
                              right: null,
                              bottom: null,
                              width: 342.0,
                              height: 146.0,
                              child: GeneratedRectangle153Widget23(),
                            ),
                            Positioned(
                              left: 1633.0,
                              top: 939.0,
                              right: null,
                              bottom: null,
                              width: 236.0,
                              height: 70.47262573242188,
                              child: GeneratedBeliSekarangWidget38(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
