import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget24/generated/GeneratedRectangle77Widget24.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget24/generated/GeneratedRectangle174Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget24/generated/GeneratedTennisball1Widget24.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget24/generated/GeneratedKeluarWidget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget24/generated/GeneratedRectangle139Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget24/generated/GeneratedBatalWidget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget24/generated/GeneratedRectangle175Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget24/generated/GeneratedBatalWidget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget24/generated/GeneratedRectangle138Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget24/generated/GeneratedApakahandayakinlogoutsebagaiguestWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget24/generated/GeneratedArrowright113Widget39.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget24/generated/GeneratedKeluarWidget7.dart';

/* Frame IMINN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIMINNWidget24 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1080.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 1080.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 690.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedTennisball1Widget24(),
                            ),
                            Positioned(
                              left: 1849.0,
                              top: 174.0,
                              right: null,
                              bottom: null,
                              width: 13.0,
                              height: 13.0,
                              child: GeneratedArrowright113Widget39(),
                            ),
                            Positioned(
                              left: 669.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 283.0,
                              child: GeneratedRectangle77Widget24(),
                            ),
                            Positioned(
                              left: 507.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 957.0,
                              height: 246.0,
                              child:
                                  GeneratedApakahandayakinlogoutsebagaiguestWidget(),
                            ),
                            Positioned(
                              left: 625.0,
                              top: 611.0,
                              right: null,
                              bottom: null,
                              width: 311.0,
                              height: 127.0,
                              child: GeneratedRectangle138Widget8(),
                            ),
                            Positioned(
                              left: 1029.0,
                              top: 611.0,
                              right: null,
                              bottom: null,
                              width: 311.0,
                              height: 127.0,
                              child: GeneratedRectangle139Widget5(),
                            ),
                            Positioned(
                              left: 629.0,
                              top: 624.0,
                              right: null,
                              bottom: null,
                              width: 312.0,
                              height: 132.0,
                              child: GeneratedBatalWidget5(),
                            ),
                            Positioned(
                              left: 1033.0,
                              top: 624.0,
                              right: null,
                              bottom: null,
                              width: 312.0,
                              height: 119.0,
                              child: GeneratedKeluarWidget6(),
                            ),
                            Positioned(
                              left: 618.0,
                              top: 598.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 153.0,
                              child: GeneratedRectangle174Widget4(),
                            ),
                            Positioned(
                              left: 629.0,
                              top: 624.0,
                              right: null,
                              bottom: null,
                              width: 312.0,
                              height: 132.0,
                              child: GeneratedBatalWidget6(),
                            ),
                            Positioned(
                              left: 1027.0,
                              top: 598.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 153.0,
                              child: GeneratedRectangle175Widget3(),
                            ),
                            Positioned(
                              left: 1033.0,
                              top: 624.0,
                              right: null,
                              bottom: null,
                              width: 312.0,
                              height: 119.0,
                              child: GeneratedKeluarWidget7(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
