import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup40widget12/generated/GeneratedCODWidget12.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup40widget12/generated/GeneratedGroup15Widget11.dart';

/* Group Group 40
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup40Widget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1152.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 1920.0,
                    height: 1147.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 1920.0,
                            height: 1080.0,
                            child: GeneratedGroup15Widget11(),
                          ),
                          Positioned(
                            left: 406.0,
                            top: 925.0,
                            right: null,
                            bottom: null,
                            width: 403.0,
                            height: 227.0,
                            child: GeneratedCODWidget12(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
