import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedLine36Widget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle121Widget19.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle110Widget21.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedTennisball1Widget44.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedPSGWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedLine41Widget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle123Widget19.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle113Widget28.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle120Widget16.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedLine43Widget20.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedKonfirmasiPembayaranWidget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedLine38Widget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedBankWidget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle112Widget18.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedLine1Widget25.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedLine37Widget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle128Widget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedLine39Widget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedMetodePembayaranWidget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedBankWidget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedLine40Widget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedArrowright114Widget21.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedImage1Widget19.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle197Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedLine44Widget20.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle196Widget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedArrowright113Widget58.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle111Widget18.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedAlamatpengirimanNama62Widget12.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle114Widget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle122Widget16.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle109Widget26.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle78Widget23.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle198Widget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedTotalPembayaranRp155000Widget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget44/generated/GeneratedRectangle77Widget44.dart';

/* Frame IMINN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIMINNWidget44 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1169.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 1080.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 100.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 1.0,
                              child: GeneratedLine1Widget25(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 690.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedTennisball1Widget44(),
                            ),
                            Positioned(
                              left: 1849.0,
                              top: 174.0,
                              right: null,
                              bottom: null,
                              width: 13.0,
                              height: 13.0,
                              child: GeneratedArrowright113Widget58(),
                            ),
                            Positioned(
                              left: 1845.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 13.0,
                              height: 13.0,
                              child: GeneratedArrowright114Widget21(),
                            ),
                            Positioned(
                              left: 669.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 283.0,
                              child: GeneratedRectangle77Widget44(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 145.0,
                              child: GeneratedImage1Widget19(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 355.0,
                              right: null,
                              bottom: null,
                              width: 176.0,
                              height: 42.0,
                              child: GeneratedRectangle109Widget26(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 355.0,
                              right: null,
                              bottom: null,
                              width: 176.0,
                              height: 42.0,
                              child: GeneratedRectangle110Widget21(),
                            ),
                            Positioned(
                              left: 406.0,
                              top: 353.0,
                              right: null,
                              bottom: null,
                              width: 176.0,
                              height: 42.0,
                              child: GeneratedRectangle111Widget18(),
                            ),
                            Positioned(
                              left: 609.0,
                              top: 353.0,
                              right: null,
                              bottom: null,
                              width: 176.0,
                              height: 42.0,
                              child: GeneratedRectangle112Widget18(),
                            ),
                            Positioned(
                              left: 781.9942626953125,
                              top: 160.0,
                              right: null,
                              bottom: null,
                              width: 176.0,
                              height: 42.0,
                              child: GeneratedRectangle113Widget28(),
                            ),
                            Positioned(
                              left: 778.9942626953125,
                              top: -35.0,
                              right: null,
                              bottom: null,
                              width: 176.0,
                              height: 42.0,
                              child: GeneratedRectangle114Widget9(),
                            ),
                            Positioned(
                              left: 1153.0,
                              top: 58.0,
                              right: null,
                              bottom: null,
                              width: 472.0,
                              height: 593.0,
                              child: GeneratedRectangle78Widget23(),
                            ),
                            Positioned(
                              left: 1029.0,
                              top: 690.0,
                              right: null,
                              bottom: null,
                              width: 724.0,
                              height: 130.0,
                              child: GeneratedPSGWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 145.0,
                              child: GeneratedRectangle120Widget16(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 173.6778564453125,
                              height: 1.0,
                              child: GeneratedLine36Widget15(),
                            ),
                            Positioned(
                              left: 88.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 153.68798828125,
                              height: 1.0,
                              child: GeneratedLine37Widget13(),
                            ),
                            Positioned(
                              left: -5.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 720.0,
                              height: 337.0,
                              child: GeneratedRectangle121Widget19(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 144.0,
                              child: GeneratedRectangle122Widget16(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 199.4091339111328,
                              height: 1.0,
                              child: GeneratedLine38Widget13(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 205.1048583984375,
                              height: 1.0,
                              child: GeneratedLine39Widget13(),
                            ),
                            Positioned(
                              left: 1153.0,
                              top: 54.0,
                              right: null,
                              bottom: null,
                              width: 472.0,
                              height: 597.0,
                              child: GeneratedRectangle123Widget19(),
                            ),
                            Positioned(
                              left: 1624.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 753.3823852539062,
                              height: 1.0,
                              child: GeneratedLine40Widget13(),
                            ),
                            Positioned(
                              left: 1156.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 760.1480102539062,
                              height: 1.0,
                              child: GeneratedLine41Widget15(),
                            ),
                            Positioned(
                              left: 323.0,
                              top: 587.0,
                              right: null,
                              bottom: null,
                              width: 410.201171875,
                              height: 1.0,
                              child: GeneratedLine43Widget20(),
                            ),
                            Positioned(
                              left: 323.0,
                              top: 587.0,
                              right: null,
                              bottom: null,
                              width: 421.0581970214844,
                              height: 1.0,
                              child: GeneratedLine44Widget20(),
                            ),
                            Positioned(
                              left: 1371.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 550.0,
                              height: 176.0,
                              child: GeneratedRectangle128Widget11(),
                            ),
                            Positioned(
                              left: 1371.0,
                              top: 969.0,
                              right: null,
                              bottom: null,
                              width: 548.0,
                              height: 171.0,
                              child: GeneratedKonfirmasiPembayaranWidget15(),
                            ),
                            Positioned(
                              left: 846.0,
                              top: 882.0,
                              right: null,
                              bottom: null,
                              width: 486.0,
                              height: 171.0,
                              child: GeneratedTotalPembayaranRp155000Widget15(),
                            ),
                            Positioned(
                              left: 174.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 543.0,
                              height: 339.0,
                              child: GeneratedAlamatpengirimanNama62Widget12(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 587.0,
                              right: null,
                              bottom: null,
                              width: 804.0,
                              height: 493.0,
                              child: GeneratedRectangle196Widget13(),
                            ),
                            Positioned(
                              left: 395.0,
                              top: 645.0,
                              right: null,
                              bottom: null,
                              width: 409.0,
                              height: 249.0,
                              child: GeneratedMetodePembayaranWidget15(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 408.0,
                              height: 224.0,
                              child: GeneratedRectangle197Widget7(),
                            ),
                            Positioned(
                              left: 406.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 398.0,
                              height: 224.0,
                              child: GeneratedRectangle198Widget13(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 938.0,
                              right: null,
                              bottom: null,
                              width: 411.0,
                              height: 231.0,
                              child: GeneratedBankWidget10(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 938.0,
                              right: null,
                              bottom: null,
                              width: 411.0,
                              height: 231.0,
                              child: GeneratedBankWidget11(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
