import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox13widget/generated/GeneratedGroup40Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox13widget/generated/GeneratedGroup27Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox13widget/generated/GeneratedRectangle164Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox13widget/generated/GeneratedLine17Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox13widget/generated/GeneratedLine16Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox13widget/generated/GeneratedKeranjangsayaWidget.dart';

/* Frame iPhone 11 Pro / X - 13
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX13Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 12.0,
                top: 18.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 81.0,
                child: GeneratedRectangle164Widget2(),
              ),
              Positioned(
                left: 112.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 82.0,
                child: GeneratedKeranjangsayaWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 18.0,
                right: null,
                bottom: null,
                width: 113.84638977050781,
                height: 1.0,
                child: GeneratedLine16Widget(),
              ),
              Positioned(
                left: 93.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 111.0720443725586,
                height: 1.0,
                child: GeneratedLine17Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 100.0,
                child: GeneratedGroup27Widget2(),
              ),
              Positioned(
                left: 267.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 49.0,
                child: GeneratedGroup40Widget1(),
              )
            ]),
      ),
    ));
  }
}
