import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox25widget1/generated/GeneratediconarrowbackoutlineWidget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox25widget1/generated/GeneratedLetstakeyourjerseyhomeWidget25.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox25widget1/generated/GeneratedGroup39Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox25widget1/generated/GeneratedRectangle73Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox25widget1/generated/GeneratedGroup44Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox25widget1/generated/GeneratedLine21Widget3.dart';

/* Frame iPhone 11 Pro / X - 25
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX25Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 37.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 146.0,
                child: GeneratedRectangle73Widget4(),
              ),
              Positioned(
                left: 208.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 237.15040588378906,
                child: GeneratedGroup39Widget3(),
              ),
              Positioned(
                left: 19.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 395.0,
                child: GeneratedGroup44Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.013333333333333334,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 375.0013427734375,
                height: 1.0,
                child: GeneratedLine21Widget3(),
              ),
              Positioned(
                left: 27.0,
                top: -48.0,
                right: null,
                bottom: null,
                width: 386.2053527832031,
                height: 40.0,
                child: GeneratedLetstakeyourjerseyhomeWidget25(),
              )
            ]),
      ),
    ));
  }
}
