import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget2/generated/GeneratedRectangle137Widget22.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget2/generated/GeneratedLogoutWidget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget2/generated/GeneratedGroup45Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget2/generated/GeneratedCongratulationsyourpaymenthasbeensuccessfulWidget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget2/generated/GeneratedEllipse9Widget5.dart';

/* Frame iPhone 11 Pro / X - 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX14Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 27.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 138.0,
                child:
                    GeneratedCongratulationsyourpaymenthasbeensuccessfulWidget1(),
              ),
              Positioned(
                left: 89.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 177.0,
                child: GeneratedEllipse9Widget5(),
              ),
              Positioned(
                left: 268.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 53.0,
                child: GeneratedRectangle137Widget22(),
              ),
              Positioned(
                left: 205.0,
                top: 766.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 65.0,
                child: GeneratedLogoutWidget15(),
              ),
              Positioned(
                left: 110.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 88.0,
                child: GeneratedGroup45Widget6(),
              )
            ]),
      ),
    ));
  }
}
