import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop33widget1/generated/GeneratedLine65Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop33widget1/generated/GeneratedRectangle137Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop33widget1/generated/GeneratedRectangle173Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop33widget1/generated/GeneratedSelamatpembayaranandasudahberhasilWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop33widget1/generated/GeneratedOkeWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop33widget1/generated/GeneratedLine66Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop33widget1/generated/GeneratedRectangle172Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop33widget1/generated/GeneratedSelamatpembayaranandasudahberhasilWidget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop33widget1/generated/GeneratedRectangle171Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop33widget1/generated/GeneratedLogoutWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop33widget1/generated/GeneratedEllipse9Widget1.dart';

/* Frame Desktop - 33
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop33Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1037.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 54.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 1254.0,
                              height: 202.0,
                              child:
                                  GeneratedSelamatpembayaranandasudahberhasilWidget1(),
                            ),
                            Positioned(
                              left: 516.0,
                              top: 360.0,
                              right: null,
                              bottom: null,
                              width: 352.0,
                              height: 328.0,
                              child: GeneratedEllipse9Widget1(),
                            ),
                            Positioned(
                              left: 1129.0,
                              top: 891.0,
                              right: null,
                              bottom: null,
                              width: 311.0,
                              height: 133.0,
                              child: GeneratedRectangle137Widget4(),
                            ),
                            Positioned(
                              left: 105.0,
                              top: 79.0,
                              right: null,
                              bottom: null,
                              width: 1217.0,
                              height: 241.0,
                              child: GeneratedRectangle171Widget(),
                            ),
                            Positioned(
                              left: 483.0,
                              top: 360.0,
                              right: null,
                              bottom: null,
                              width: 445.0,
                              height: 355.0,
                              child: GeneratedRectangle172Widget(),
                            ),
                            Positioned(
                              left: 482.0,
                              top: 359.0,
                              right: null,
                              bottom: null,
                              width: 570.6592407226562,
                              height: 1.0,
                              child: GeneratedLine65Widget(),
                            ),
                            Positioned(
                              left: 923.0,
                              top: 361.0,
                              right: null,
                              bottom: null,
                              width: 564.7265014648438,
                              height: 1.0,
                              child: GeneratedLine66Widget(),
                            ),
                            Positioned(
                              left: 533.0,
                              top: 760.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 120.0,
                              child: GeneratedRectangle173Widget(),
                            ),
                            Positioned(
                              left: 533.0,
                              top: 757.0,
                              right: null,
                              bottom: null,
                              width: 366.0,
                              height: 128.0,
                              child: GeneratedOkeWidget3(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 1254.0,
                              height: 202.0,
                              child:
                                  GeneratedSelamatpembayaranandasudahberhasilWidget2(),
                            ),
                            Positioned(
                              left: 1127.0,
                              top: 891.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 146.0,
                              child: GeneratedLogoutWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
