import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop22widget2/generated/GeneratedGroup38Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop22widget2/generated/GeneratedBuynowWidget26.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop22widget2/generated/GeneratedRectangle153Widget39.dart';

/* Frame Desktop - 22
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop22Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1027.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -53.0,
                              top: -28.0,
                              right: null,
                              bottom: null,
                              width: 1493.0,
                              height: 1052.0,
                              child: GeneratedGroup38Widget2(),
                            ),
                            Positioned(
                              left: 1174.0,
                              top: 864.0,
                              right: null,
                              bottom: null,
                              width: 266.0,
                              height: 163.0,
                              child: GeneratedRectangle153Widget39(),
                            ),
                            Positioned(
                              left: 1219.0,
                              top: 901.0,
                              right: null,
                              bottom: null,
                              width: 184.14053344726562,
                              height: 70.47262573242188,
                              child: GeneratedBuynowWidget26(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
