import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup23widget4/generated/GeneratedGroup16Widget4.dart';

/* Group Group 23
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup23Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1080.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 1765.5172119140625,
                    height: 1080.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 1765.5172119140625,
                            height: 1080.0,
                            child: GeneratedGroup16Widget4(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
