import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop1widget/generated/GeneratedGroup43Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop1widget/generated/GeneratedGroup44Widget.dart';

/* Frame Desktop - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 5.371798992156982,
                              top: 3.1787261962890625,
                              right: null,
                              bottom: null,
                              width: 1424.46484375,
                              height: 814.79833984375,
                              child: GeneratedGroup43Widget(),
                            ),
                            Positioned(
                              left: 1012.0,
                              top: 396.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 380.0,
                              child: GeneratedGroup44Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
