import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget1/generated/GeneratedGroup21Widget19.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget1/generated/GeneratediconarrowbackoutlineWidget22.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget1/generated/GeneratedGroup13Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget1/generated/GeneratedUntitled11Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget1/generated/GeneratedRectangle225Widget11.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget1/generated/GeneratedLogoutWidget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget1/generated/GeneratedGroup10Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget1/generated/GeneratedLetstakeyourjerseyhomeWidget41.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget1/generated/GeneratedEditProfilWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget1/generated/GeneratedRectangle226Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget1/generated/GeneratedGroup12Widget33.dart';

/* Frame iPhone 11 Pro / X - 32
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX32Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 402.2053527832031,
                height: 120.96703338623047,
                child: GeneratedGroup21Widget19(),
              ),
              Positioned(
                left: 18.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 386.2053527832031,
                height: 40.0,
                child: GeneratedLetstakeyourjerseyhomeWidget41(),
              ),
              Positioned(
                left: 31.0,
                top: 179.73095703125,
                right: null,
                bottom: null,
                width: 118.49947357177734,
                height: 309.0075988769531,
                child: GeneratedUntitled11Widget2(),
              ),
              Positioned(
                left: 15.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 200.0,
                child: GeneratedGroup10Widget8(),
              ),
              Positioned(
                left: 190.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 198.0,
                child: GeneratedGroup12Widget33(),
              ),
              Positioned(
                left: 174.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 216.0,
                child: GeneratedGroup13Widget7(),
              ),
              Positioned(
                left: 311.0,
                top: 4.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 24.0,
                child: GeneratedRectangle225Widget11(),
              ),
              Positioned(
                left: 311.0,
                top: 7.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 25.0,
                child: GeneratedLogoutWidget13(),
              ),
              Positioned(
                left: 70.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 24.0,
                child: GeneratedRectangle226Widget4(),
              ),
              Positioned(
                left: 72.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 17.0,
                child: GeneratedEditProfilWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.024,
                        y: constraints.maxHeight * -0.012315270935960592,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget22(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
