import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedRectangle158Widget12.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedGroup50Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedRectangle53Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedGroup52Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedRectangle56Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedLine1Widget35.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedGroup47Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedArrowright114Widget29.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedEditProfileWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedRectangle1Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedSearch141Widget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedRectangle137Widget20.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedArrowright113Widget80.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedLogoutWidget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedGroup53Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedGroup63Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedRectangle99Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedWELCOMETOAFFZONEWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedSearchWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedGroup51Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedRectangle6Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop60widget/generated/GeneratedLetstakeyourjerseyhomeWidget36.dart';

/* Frame Desktop - 60
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop60Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1541.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -7.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 1041.0,
                              child: GeneratedRectangle1Widget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 101.0,
                              right: null,
                              bottom: null,
                              width: 100.99993896484375,
                              height: 1440.0,
                              child: GeneratedRectangle6Widget7(),
                            ),
                            Positioned(
                              left: 86.0,
                              top: 23.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 1.0,
                              child: GeneratedLine1Widget35(),
                            ),
                            Positioned(
                              left: 538.0,
                              top: 46.0,
                              right: null,
                              bottom: null,
                              width: 492.0,
                              height: 48.0,
                              child: GeneratedRectangle53Widget7(),
                            ),
                            Positioned(
                              left: 974.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 39.0,
                              child: GeneratedSearch141Widget10(),
                            ),
                            Positioned(
                              left: 582.0,
                              top: 45.0,
                              right: null,
                              bottom: null,
                              width: 344.0,
                              height: 35.0,
                              child: GeneratedSearchWidget3(),
                            ),
                            Positioned(
                              left: 488.0,
                              top: 148.0,
                              right: null,
                              bottom: null,
                              width: 687.0,
                              height: 325.0,
                              child: GeneratedRectangle56Widget7(),
                            ),
                            Positioned(
                              left: 1398.0,
                              top: 191.0,
                              right: null,
                              bottom: null,
                              width: 10.0,
                              height: 12.0,
                              child: GeneratedArrowright113Widget80(),
                            ),
                            Positioned(
                              left: 1395.0,
                              top: 203.0,
                              right: null,
                              bottom: null,
                              width: 10.0,
                              height: 12.0,
                              child: GeneratedArrowright114Widget29(),
                            ),
                            Positioned(
                              left: 560.0,
                              top: 572.0,
                              right: null,
                              bottom: null,
                              width: 220.84158325195312,
                              height: 321.0308532714844,
                              child: GeneratedGroup50Widget3(),
                            ),
                            Positioned(
                              left: 791.0,
                              top: 558.0,
                              right: null,
                              bottom: null,
                              width: 219.0,
                              height: 348.0,
                              child: GeneratedGroup51Widget3(),
                            ),
                            Positioned(
                              left: 1019.0,
                              top: 571.0,
                              right: null,
                              bottom: null,
                              width: 200.0,
                              height: 343.0,
                              child: GeneratedGroup53Widget3(),
                            ),
                            Positioned(
                              left: 1240.0,
                              top: 567.0,
                              right: null,
                              bottom: null,
                              width: 200.0,
                              height: 360.0,
                              child: GeneratedGroup52Widget3(),
                            ),
                            Positioned(
                              left: 358.0,
                              top: 571.0,
                              right: null,
                              bottom: null,
                              width: 207.0,
                              height: 326.0,
                              child: GeneratedGroup47Widget4(),
                            ),
                            Positioned(
                              left: 68.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 828.0,
                              child: GeneratedGroup63Widget1(),
                            ),
                            Positioned(
                              left: 607.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 457.0,
                              height: 89.0,
                              child: GeneratedWELCOMETOAFFZONEWidget3(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 23.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 78.0,
                              child: GeneratedRectangle99Widget7(),
                            ),
                            Positioned(
                              left: 629.0,
                              top: 316.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 84.0,
                              child: GeneratedLetstakeyourjerseyhomeWidget36(),
                            ),
                            Positioned(
                              left: 86.0,
                              top: 23.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 70.0,
                              child: GeneratedRectangle158Widget12(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 31.0,
                              right: null,
                              bottom: null,
                              width: 186.0,
                              height: 60.0,
                              child: GeneratedEditProfileWidget3(),
                            ),
                            Positioned(
                              left: 1217.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 191.0,
                              height: 63.0,
                              child: GeneratedRectangle137Widget20(),
                            ),
                            Positioned(
                              left: 1213.0,
                              top: 33.0,
                              right: null,
                              bottom: null,
                              width: 200.0,
                              height: 71.0,
                              child: GeneratedLogoutWidget11(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
