import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox46widget/generated/GeneratediconmessagecircleWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox46widget/generated/GeneratediconarrowbackoutlineWidget12.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox46widget/generated/GeneratedGroup13Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox46widget/generated/GeneratedLetstakeyourjersethomeWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox46widget/generated/GeneratedGroup43Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox46widget/generated/GeneratedGroup46Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox46widget/generated/GeneratedRectangle228Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox46widget/generated/GeneratediconshoppingcartWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame iPhone 11 Pro / X - 46
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX46Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 68.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 239.0,
                height: 330.0,
                child: GeneratedGroup43Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 65.0,
                child: GeneratedRectangle228Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.25066666666666665;

                  final double height =
                      constraints.maxHeight * 0.08251231527093596;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6053333333333333,
                        y: constraints.maxHeight * 0.9174876847290641,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconshoppingcartWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.21866666666666668;

                  final double height =
                      constraints.maxHeight * 0.07758620689655173;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.416,
                        y: constraints.maxHeight * 0.9224137931034483,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconmessagecircleWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 8.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 77.0,
                child: GeneratedLetstakeyourjersethomeWidget3(),
              ),
              Positioned(
                left: 285.0,
                top: 752.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 52.0,
                child: GeneratedGroup46Widget2(),
              ),
              Positioned(
                left: 28.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 120.0,
                child: GeneratedGroup13Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.018666666666666668,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget12(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
