import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedRectangle123Widget22.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedPasswordWidget26.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedRectangle120Widget19.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedRectangle122Widget22.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedRectangle121Widget25.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedEmailaddressWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedRegisterWidget19.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedPhonenumberWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedRectangle125Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedRectangle124Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedCompleteaddressWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedFullnameWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop58widget/generated/GeneratedConfirmationWidget8.dart';

/* Frame Desktop - 58
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop58Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 125.0,
                              child: GeneratedRegisterWidget19(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 123.0,
                              right: null,
                              bottom: null,
                              width: 1020.0,
                              height: 115.0,
                              child: GeneratedRectangle120Widget19(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 301.0,
                              right: null,
                              bottom: null,
                              width: 1020.0,
                              height: 115.0,
                              child: GeneratedRectangle121Widget25(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 479.0,
                              right: null,
                              bottom: null,
                              width: 1020.0,
                              height: 115.0,
                              child: GeneratedRectangle122Widget22(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 657.0,
                              right: null,
                              bottom: null,
                              width: 1020.0,
                              height: 115.0,
                              child: GeneratedRectangle123Widget22(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 835.0,
                              right: null,
                              bottom: null,
                              width: 1020.0,
                              height: 115.0,
                              child: GeneratedRectangle124Widget8(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 142.0,
                              right: null,
                              bottom: null,
                              width: 1022.0,
                              height: 116.0,
                              child: GeneratedFullnameWidget2(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 314.0,
                              right: null,
                              bottom: null,
                              width: 1031.0,
                              height: 126.0,
                              child: GeneratedCompleteaddressWidget2(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 492.0,
                              right: null,
                              bottom: null,
                              width: 1022.0,
                              height: 91.0,
                              child: GeneratedPhonenumberWidget2(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 673.0,
                              right: null,
                              bottom: null,
                              width: 1031.0,
                              height: 123.0,
                              child: GeneratedEmailaddressWidget2(),
                            ),
                            Positioned(
                              left: 132.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 1017.0,
                              height: 114.0,
                              child: GeneratedPasswordWidget26(),
                            ),
                            Positioned(
                              left: 1165.0,
                              top: 835.0,
                              right: null,
                              bottom: null,
                              width: 246.0,
                              height: 111.0,
                              child: GeneratedRectangle125Widget7(),
                            ),
                            Positioned(
                              left: 1190.0,
                              top: 865.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 102.0,
                              child: GeneratedConfirmationWidget8(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
