import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox16widget2/generated/GeneratedCommentsSentWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox16widget2/generated/GeneratedRectangle197Widget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox16widget2/generated/GeneratedOkeWidget16.dart';

/* Frame iPhone 11 Pro / X - 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX16Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 66.0,
                child: GeneratedCommentsSentWidget2(),
              ),
              Positioned(
                left: 111.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 67.0,
                child: GeneratedRectangle197Widget11(),
              ),
              Positioned(
                left: 132.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 56.0,
                child: GeneratedOkeWidget16(),
              )
            ]),
      ),
    ));
  }
}
