import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedAlamatLengkapWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedPasswordWidget14.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedTennisball1Widget28.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedSearch141Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedAlamatEmailWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedNamaLengkapWidget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle120Widget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle124Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle137Widget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle134Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle138Widget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedAlamatLengkapWidget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle123Widget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle133Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle136Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedNomorTeleponWidget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedNomorTeleponWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRegisterWidget12.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedLine1Widget19.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle77Widget28.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedPasswordWidget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle132Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle125Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedNamaLengkapWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedAlamatEmailWidget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle121Widget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedKonfirmasiWidget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle135Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget28/generated/GeneratedRectangle122Widget10.dart';

/* Frame IMINN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIMINNWidget28 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1080.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 1080.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 100.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 1.0,
                              child: GeneratedLine1Widget19(),
                            ),
                            Positioned(
                              left: 1309.0,
                              top: 44.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedSearch141Widget7(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 690.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedTennisball1Widget28(),
                            ),
                            Positioned(
                              left: 669.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 283.0,
                              child: GeneratedRectangle77Widget28(),
                            ),
                            Positioned(
                              left: 234.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 1020.0,
                              height: 115.0,
                              child: GeneratedRectangle120Widget10(),
                            ),
                            Positioned(
                              left: 234.0,
                              top: 336.0,
                              right: null,
                              bottom: null,
                              width: 1020.0,
                              height: 115.0,
                              child: GeneratedRectangle121Widget13(),
                            ),
                            Positioned(
                              left: 234.0,
                              top: 514.0,
                              right: null,
                              bottom: null,
                              width: 1020.0,
                              height: 115.0,
                              child: GeneratedRectangle122Widget10(),
                            ),
                            Positioned(
                              left: 234.0,
                              top: 692.0,
                              right: null,
                              bottom: null,
                              width: 1020.0,
                              height: 115.0,
                              child: GeneratedRectangle123Widget13(),
                            ),
                            Positioned(
                              left: 234.0,
                              top: 870.0,
                              right: null,
                              bottom: null,
                              width: 1020.0,
                              height: 115.0,
                              child: GeneratedRectangle124Widget6(),
                            ),
                            Positioned(
                              left: 234.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 1022.0,
                              height: 116.0,
                              child: GeneratedNamaLengkapWidget4(),
                            ),
                            Positioned(
                              left: 225.0,
                              top: 327.0,
                              right: null,
                              bottom: null,
                              width: 1031.0,
                              height: 126.0,
                              child: GeneratedAlamatLengkapWidget4(),
                            ),
                            Positioned(
                              left: 234.0,
                              top: 540.0,
                              right: null,
                              bottom: null,
                              width: 1022.0,
                              height: 91.0,
                              child: GeneratedNomorTeleponWidget4(),
                            ),
                            Positioned(
                              left: 225.0,
                              top: 686.0,
                              right: null,
                              bottom: null,
                              width: 1031.0,
                              height: 123.0,
                              child: GeneratedAlamatEmailWidget4(),
                            ),
                            Positioned(
                              left: 239.0,
                              top: 873.0,
                              right: null,
                              bottom: null,
                              width: 1017.0,
                              height: 114.0,
                              child: GeneratedPasswordWidget13(),
                            ),
                            Positioned(
                              left: 1333.0,
                              top: 807.0,
                              right: null,
                              bottom: null,
                              width: 556.0,
                              height: 131.0,
                              child: GeneratedRectangle125Widget5(),
                            ),
                            Positioned(
                              left: 238.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 1016.0,
                              height: 117.0,
                              child: GeneratedRectangle133Widget8(),
                            ),
                            Positioned(
                              left: 234.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 1022.0,
                              height: 116.0,
                              child: GeneratedNamaLengkapWidget5(),
                            ),
                            Positioned(
                              left: 225.0,
                              top: 327.0,
                              right: null,
                              bottom: null,
                              width: 1016.0,
                              height: 117.0,
                              child: GeneratedRectangle134Widget8(),
                            ),
                            Positioned(
                              left: 225.0,
                              top: 327.0,
                              right: null,
                              bottom: null,
                              width: 1031.0,
                              height: 126.0,
                              child: GeneratedAlamatLengkapWidget5(),
                            ),
                            Positioned(
                              left: 240.0,
                              top: 526.0,
                              right: null,
                              bottom: null,
                              width: 1016.0,
                              height: 117.0,
                              child: GeneratedRectangle135Widget2(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: 514.0,
                              right: null,
                              bottom: null,
                              width: 1022.0,
                              height: 91.0,
                              child: GeneratedNomorTeleponWidget5(),
                            ),
                            Positioned(
                              left: 240.0,
                              top: 693.0,
                              right: null,
                              bottom: null,
                              width: 1016.0,
                              height: 117.0,
                              child: GeneratedRectangle136Widget4(),
                            ),
                            Positioned(
                              left: 239.0,
                              top: 683.0,
                              right: null,
                              bottom: null,
                              width: 1031.0,
                              height: 123.0,
                              child: GeneratedAlamatEmailWidget5(),
                            ),
                            Positioned(
                              left: 238.0,
                              top: 868.0,
                              right: null,
                              bottom: null,
                              width: 1016.0,
                              height: 117.0,
                              child: GeneratedRectangle137Widget13(),
                            ),
                            Positioned(
                              left: 253.0,
                              top: 862.0,
                              right: null,
                              bottom: null,
                              width: 1017.0,
                              height: 114.0,
                              child: GeneratedPasswordWidget14(),
                            ),
                            Positioned(
                              left: 1305.0,
                              top: 793.0,
                              right: null,
                              bottom: null,
                              width: 611.0,
                              height: 145.0,
                              child: GeneratedRectangle138Widget9(),
                            ),
                            Positioned(
                              left: 178.0,
                              top: 18.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 100.0,
                              child: GeneratedRectangle132Widget8(),
                            ),
                            Positioned(
                              left: 178.0,
                              top: 23.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 123.0,
                              child: GeneratedRegisterWidget12(),
                            ),
                            Positioned(
                              left: 1333.0,
                              top: 810.0,
                              right: null,
                              bottom: null,
                              width: 621.0,
                              height: 148.0,
                              child: GeneratedKonfirmasiWidget11(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
