import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox16widget1/generated/GeneratedRectangle197Widget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox16widget1/generated/GeneratedKomentarTerkirimWidget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox16widget1/generated/GeneratedOkeWidget9.dart';

/* Frame iPhone 11 Pro / X - 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX16Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 66.0,
                child: GeneratedKomentarTerkirimWidget5(),
              ),
              Positioned(
                left: 95.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 83.0,
                child: GeneratedRectangle197Widget9(),
              ),
              Positioned(
                left: 91.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 93.0,
                child: GeneratedOkeWidget9(),
              )
            ]),
      ),
    ));
  }
}
