import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop29widget2/generated/GeneratedLine49Widget12.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop29widget2/generated/GeneratedGroup61Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop29widget2/generated/GeneratedRectangle119Widget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop29widget2/generated/GeneratedGroup4Widget34.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop29widget2/generated/GeneratedPaymentconfirmationWidget5.dart';

/* Frame Desktop - 29
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop29Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1029.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 3.740234375,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 1262.7117919921875,
                              height: 971.8591918945312,
                              child: GeneratedGroup61Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 813.0,
                              right: null,
                              bottom: null,
                              width: 596.6805419921875,
                              height: 214.21981811523438,
                              child: GeneratedGroup4Widget34(),
                            ),
                            Positioned(
                              left: 1099.0,
                              top: 880.0,
                              right: null,
                              bottom: null,
                              width: 337.0,
                              height: 132.0,
                              child: GeneratedRectangle119Widget13(),
                            ),
                            Positioned(
                              left: 1118.0,
                              top: 865.0,
                              right: null,
                              bottom: null,
                              width: 289.0,
                              height: 164.0,
                              child: GeneratedPaymentconfirmationWidget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 842.9560546875,
                              right: null,
                              bottom: null,
                              width: 1453.002685546875,
                              height: 0.4561041295528412,
                              child: GeneratedLine49Widget12(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
