import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup43widget2/generated/GeneratedRectangle210Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup43widget2/generated/GeneratedRectangle214Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup43widget2/generated/GeneratedRectangle211Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup43widget2/generated/GeneratedRectangle209Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup43widget2/generated/GeneratedRectangle215Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup43widget2/generated/GeneratedGroup32Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup43widget2/generated/GeneratedRectangle201Widget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup43widget2/generated/GeneratedRectangle212Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup43widget2/generated/GeneratedPPilihFotoWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup43widget2/generated/GeneratedRectangle213Widget4.dart';

/* Group Group 43
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup43Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1080.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 1920.0,
                    height: 1080.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 1920.0,
                            height: 1080.0,
                            child: GeneratedGroup32Widget7(),
                          ),
                          Positioned(
                            left: 326.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 1025.0,
                            height: 201.0,
                            child: GeneratedPPilihFotoWidget2(),
                          ),
                          Positioned(
                            left: 6.0,
                            top: 199.0,
                            right: null,
                            bottom: null,
                            width: 481.0,
                            height: 402.0,
                            child: GeneratedRectangle201Widget9(),
                          ),
                          Positioned(
                            left: 6.0,
                            top: 599.0,
                            right: null,
                            bottom: null,
                            width: 481.0,
                            height: 402.0,
                            child: GeneratedRectangle212Widget4(),
                          ),
                          Positioned(
                            left: 485.0,
                            top: 599.0,
                            right: null,
                            bottom: null,
                            width: 481.0,
                            height: 402.0,
                            child: GeneratedRectangle213Widget4(),
                          ),
                          Positioned(
                            left: 964.0,
                            top: 599.0,
                            right: null,
                            bottom: null,
                            width: 473.0,
                            height: 402.0,
                            child: GeneratedRectangle214Widget4(),
                          ),
                          Positioned(
                            left: 1435.0,
                            top: 599.0,
                            right: null,
                            bottom: null,
                            width: 481.0,
                            height: 402.0,
                            child: GeneratedRectangle215Widget4(),
                          ),
                          Positioned(
                            left: 485.0,
                            top: 199.0,
                            right: null,
                            bottom: null,
                            width: 481.0,
                            height: 402.0,
                            child: GeneratedRectangle209Widget4(),
                          ),
                          Positioned(
                            left: 964.0,
                            top: 199.0,
                            right: null,
                            bottom: null,
                            width: 481.0,
                            height: 402.0,
                            child: GeneratedRectangle210Widget4(),
                          ),
                          Positioned(
                            left: 1435.0,
                            top: 199.0,
                            right: null,
                            bottom: null,
                            width: 487.0,
                            height: 402.0,
                            child: GeneratedRectangle211Widget4(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
