import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup27widget5/generated/GeneratedLine67Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup27widget5/generated/GeneratedLine68Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup27widget5/generated/GeneratedRectangle199Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup27widget5/generated/GeneratedGroup25Widget3.dart';

/* Group Group 27
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup27Widget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1080.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 2035.0,
                    height: 1080.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0.0),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 2035.0,
                            height: 1080.0,
                            child: GeneratedGroup25Widget3(),
                          ),
                          Positioned(
                            left: 142.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 101.0,
                            height: 111.0,
                            child: GeneratedRectangle199Widget5(),
                          ),
                          Positioned(
                            left: 142.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 148.60012817382812,
                            height: 1.0,
                            child: GeneratedLine67Widget1(),
                          ),
                          Positioned(
                            left: 243.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 144.972412109375,
                            height: 1.0,
                            child: GeneratedLine68Widget1(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
