import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget3/generated/GeneratedSendRatingWidget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget3/generated/GeneratedLine34Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget3/generated/GeneratedThankyouLadsWidget14.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget3/generated/GeneratedThankyouLadsWidget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget3/generated/GeneratedGroup10Widget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget3/generated/GeneratedRectangle157Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget3/generated/GeneratedRectangle156Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget3/generated/GeneratedSendRatingWidget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget3/generated/GeneratedLine33Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget3/generated/GeneratedRectangle158Widget16.dart';

/* Frame iPhone 11 Pro / X - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX11Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 65.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 145.0,
                child: GeneratedThankyouLadsWidget14(),
              ),
              Positioned(
                left: 38.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 76.0,
                child: GeneratedGroup10Widget11(),
              ),
              Positioned(
                left: 37.0,
                top: 507.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 81.0,
                child: GeneratedSendRatingWidget8(),
              ),
              Positioned(
                left: 70.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 207.0,
                child: GeneratedRectangle156Widget3(),
              ),
              Positioned(
                left: 63.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 145.0,
                child: GeneratedThankyouLadsWidget15(),
              ),
              Positioned(
                left: 33.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 76.0,
                child: GeneratedRectangle157Widget8(),
              ),
              Positioned(
                left: 31.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 330.1060485839844,
                height: 1.0,
                child: GeneratedLine33Widget1(),
              ),
              Positioned(
                left: 349.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 325.0107727050781,
                height: 1.0,
                child: GeneratedLine34Widget1(),
              ),
              Positioned(
                left: 37.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 75.0,
                child: GeneratedRectangle158Widget16(),
              ),
              Positioned(
                left: 44.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 77.0,
                child: GeneratedSendRatingWidget9(),
              )
            ]),
      ),
    ));
  }
}
