import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratediconcheckmarkoutlineWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratedLine18Widget15.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratedEllipse10Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratedPilihMetodePembayaranWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratedBCABANKINGWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratedVectorWidget358.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratediconarrowbackoutlineWidget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratedCODWidget14.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratedRectangle227Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratedLine19Widget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratedEllipse11Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratedOkeWidget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox32widget/generated/GeneratedLine20Widget9.dart';

/* Frame iPhone 11 Pro / X - 32
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX32Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 13.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 91.13924407958984,
                height: 50.0,
                child: GeneratedImage2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 66.94921875,
                right: null,
                bottom: null,
                width: 375.0013427734375,
                height: 1.0,
                child: GeneratedLine18Widget15(),
              ),
              Positioned(
                left: -1.0,
                top: 148.94921875,
                right: null,
                bottom: null,
                width: 375.0013427734375,
                height: 1.0,
                child: GeneratedLine19Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 230.949462890625,
                right: null,
                bottom: null,
                width: 375.0013427734375,
                height: 1.0,
                child: GeneratedLine20Widget9(),
              ),
              Positioned(
                left: 146.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 52.0,
                child: GeneratedBCABANKINGWidget(),
              ),
              Positioned(
                left: 146.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 55.0,
                child: GeneratedCODWidget14(),
              ),
              Positioned(
                left: 306.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: GeneratedEllipse10Widget2(),
              ),
              Positioned(
                left: 306.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: GeneratedEllipse11Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.088083251953125;

                  final double height =
                      constraints.maxHeight * 0.030542805864305918;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8326261393229166,
                        y: constraints.maxHeight * 0.11608957187295547,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconcheckmarkoutlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.088083251953125;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      33.031219482421875;

                  double percentHeight = 0.030542805864305918;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      24.800758361816406;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.832,
                        translateY: constraints.maxHeight * 0.21798029556650247,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget358())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.0026666666666666666,
                        y: constraints.maxHeight * 0.006157635467980296,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget11(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 111.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 28.0,
                child: GeneratedPilihMetodePembayaranWidget3(),
              ),
              Positioned(
                left: 275.0,
                top: 767.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 45.0,
                child: GeneratedRectangle227Widget1(),
              ),
              Positioned(
                left: 274.0,
                top: 777.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 52.0,
                child: GeneratedOkeWidget11(),
              )
            ]),
      ),
    ));
  }
}
