import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox66widget/generated/GeneratedRectangle87Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox66widget/generated/GeneratedRectangle132Widget21.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox66widget/generated/GeneratedShippingaddressWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox66widget/generated/GeneratedTotalpaymentRp155000Widget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox66widget/generated/GeneratedGroup22Widget12.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox66widget/generated/GeneratedRectangle122Widget27.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox66widget/generated/GeneratedPaymentconfirmationWidget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox66widget/generated/GeneratedName62JlWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox66widget/generated/GeneratedImage1Widget35.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox66widget/generated/GeneratedRectangle121Widget30.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox66widget/generated/GeneratedPSGWidget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox66widget/generated/GeneratedRectangle131Widget18.dart';

/* Frame iPhone 11 Pro / X - 66
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX66Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 231.0,
                child: GeneratedRectangle121Widget30(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 78.0,
                child: GeneratedRectangle122Widget27(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 116.0,
                child: GeneratedImage1Widget35(),
              ),
              Positioned(
                left: 99.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 118.0,
                child: GeneratedShippingaddressWidget4(),
              ),
              Positioned(
                left: 50.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 114.0,
                child: GeneratedName62JlWidget4(),
              ),
              Positioned(
                left: 166.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 58.0,
                child: GeneratedPSGWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 741.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 71.0,
                child: GeneratedGroup22Widget12(),
              ),
              Positioned(
                left: 99.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 72.0,
                child: GeneratedTotalpaymentRp155000Widget11(),
              ),
              Positioned(
                left: 268.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 53.0,
                child: GeneratedRectangle131Widget18(),
              ),
              Positioned(
                left: 268.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 53.0,
                child: GeneratedRectangle132Widget21(),
              ),
              Positioned(
                left: 257.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 91.0,
                child: GeneratedPaymentconfirmationWidget11(),
              ),
              Positioned(
                left: 99.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 274.0,
                child: GeneratedRectangle87Widget4(),
              )
            ]),
      ),
    ));
  }
}
