import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop32widget1/generated/GeneratedBatalWidget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop32widget1/generated/GeneratedKeluarWidget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop32widget1/generated/GeneratedRectangle139Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop32widget1/generated/GeneratedAreyousureyouareloggedoutasauserWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop32widget1/generated/GeneratedRectangle138Widget13.dart';

/* Frame Desktop - 32
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop32Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 290.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 862.0,
                              height: 246.0,
                              child:
                                  GeneratedAreyousureyouareloggedoutasauserWidget(),
                            ),
                            Positioned(
                              left: 421.0,
                              top: 485.0,
                              right: null,
                              bottom: null,
                              width: 221.0,
                              height: 112.0,
                              child: GeneratedRectangle138Widget13(),
                            ),
                            Positioned(
                              left: 767.0,
                              top: 486.0,
                              right: null,
                              bottom: null,
                              width: 222.0,
                              height: 112.0,
                              child: GeneratedRectangle139Widget8(),
                            ),
                            Positioned(
                              left: 409.0,
                              top: 512.0,
                              right: null,
                              bottom: null,
                              width: 251.0,
                              height: 96.0,
                              child: GeneratedBatalWidget10(),
                            ),
                            Positioned(
                              left: 724.0,
                              top: 512.0,
                              right: null,
                              bottom: null,
                              width: 312.0,
                              height: 119.0,
                              child: GeneratedKeluarWidget11(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
