import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget15/generated/GeneratedHapusWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget15/generated/GeneratedTennisball1Widget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget15/generated/GeneratedRectangle77Widget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget15/generated/GeneratedGroup26Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget15/generated/GeneratedRectangle199Widget4.dart';

/* Frame IMINN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIMINNWidget15 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1080.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 1080.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 690.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedTennisball1Widget15(),
                            ),
                            Positioned(
                              left: 669.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 283.0,
                              child: GeneratedRectangle77Widget15(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 81.0,
                              right: null,
                              bottom: null,
                              width: 1862.0,
                              height: 894.0,
                              child: GeneratedGroup26Widget7(),
                            ),
                            Positioned(
                              left: 1164.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 544.0,
                              height: 219.0,
                              child: GeneratedRectangle199Widget4(),
                            ),
                            Positioned(
                              left: 1164.0,
                              top: 396.0,
                              right: null,
                              bottom: null,
                              width: 554.0,
                              height: 224.0,
                              child: GeneratedHapusWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
