import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget27/generated/GeneratedGroup10Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget27/generated/GeneratedRectangle130Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget27/generated/GeneratedThankyouLadsWidget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget27/generated/GeneratedRectangle129Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget27/generated/GeneratedLine47Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget27/generated/GeneratedTennisball1Widget27.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget27/generated/GeneratedLine46Widget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget27/generated/GeneratedRectangle131Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget27/generated/GeneratedRectangle77Widget27.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget27/generated/GeneratedSendRatingWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget27/generated/GeneratedThankyouLadsWidget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget27/generated/GeneratedArrowright113Widget42.dart';

/* Frame IMINN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIMINNWidget27 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1080.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 1080.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 690.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedTennisball1Widget27(),
                            ),
                            Positioned(
                              left: 1849.0,
                              top: 174.0,
                              right: null,
                              bottom: null,
                              width: 13.0,
                              height: 13.0,
                              child: GeneratedArrowright113Widget42(),
                            ),
                            Positioned(
                              left: 669.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 283.0,
                              child: GeneratedRectangle77Widget27(),
                            ),
                            Positioned(
                              left: 499.0,
                              top: 304.0,
                              right: null,
                              bottom: null,
                              width: 954.0,
                              height: 120.0,
                              child: GeneratedThankyouLadsWidget5(),
                            ),
                            Positioned(
                              left: 630.0,
                              top: 540.0,
                              right: null,
                              bottom: null,
                              width: 660.0,
                              height: 132.0,
                              child: GeneratedGroup10Widget3(),
                            ),
                            Positioned(
                              left: 613.0,
                              top: 304.0,
                              right: null,
                              bottom: null,
                              width: 723.0,
                              height: 118.0,
                              child: GeneratedRectangle129Widget7(),
                            ),
                            Positioned(
                              left: 514.0,
                              top: 319.0,
                              right: null,
                              bottom: null,
                              width: 954.0,
                              height: 120.0,
                              child: GeneratedThankyouLadsWidget6(),
                            ),
                            Positioned(
                              left: 635.0,
                              top: 540.0,
                              right: null,
                              bottom: null,
                              width: 680.0,
                              height: 132.0,
                              child: GeneratedRectangle130Widget7(),
                            ),
                            Positioned(
                              left: 635.0,
                              top: 540.0,
                              right: null,
                              bottom: null,
                              width: 692.6932983398438,
                              height: 1.0,
                              child: GeneratedLine46Widget9(),
                            ),
                            Positioned(
                              left: 1315.0,
                              top: 540.0,
                              right: null,
                              bottom: null,
                              width: 692.6932983398438,
                              height: 1.0,
                              child: GeneratedLine47Widget4(),
                            ),
                            Positioned(
                              left: 667.0,
                              top: 696.0,
                              right: null,
                              bottom: null,
                              width: 617.0,
                              height: 116.0,
                              child: GeneratedRectangle131Widget7(),
                            ),
                            Positioned(
                              left: 664.0,
                              top: 716.0,
                              right: null,
                              bottom: null,
                              width: 614.0,
                              height: 126.0,
                              child: GeneratedSendRatingWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
