import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup56widget2/generated/GeneratedGroup28Widget14.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup56widget2/generated/GeneratedRectangle241Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup56widget2/generated/GeneratedOkeWidget21.dart';

/* Group Group 56
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup56Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 387.0,
      height: 836.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 812.0,
              child: GeneratedGroup28Widget14(),
            ),
            Positioned(
              left: 213.0,
              top: 754.0,
              right: null,
              bottom: null,
              width: 162.0,
              height: 58.0,
              child: GeneratedRectangle241Widget(),
            ),
            Positioned(
              left: 200.0,
              top: 764.0,
              right: null,
              bottom: null,
              width: 192.0,
              height: 77.0,
              child: GeneratedOkeWidget21(),
            )
          ]),
    ));
  }
}
