import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratedLine19Widget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratedImage2Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratediconcheckmarkoutlineWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratediconcheckmarkoutlineWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratediconarrowbackoutlineWidget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratedLine20Widget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratedEllipse13Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratedCODpayonthespotWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratedLine18Widget16.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratedBCABANKINGWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratediconcameraoutlineWidget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop55widget/generated/GeneratedChoosePaymentMethodWidget7.dart';

/* Frame Desktop - 55
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop55Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.140625;

                                final double height =
                                    constraints.maxHeight * 0.1513671875;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          -0.0006944444444444445,
                                      y: constraints.maxHeight * 0.0048828125,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratediconarrowbackoutlineWidget15(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 399.0,
                              top: 47.0,
                              right: null,
                              bottom: null,
                              width: 726.0,
                              height: 83.0,
                              child: GeneratedChoosePaymentMethodWidget7(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 159.949462890625,
                              right: null,
                              bottom: null,
                              width: 1441.0,
                              height: 1.0,
                              child: GeneratedLine18Widget16(),
                            ),
                            Positioned(
                              left: -19.0,
                              top: 377.0,
                              right: null,
                              bottom: null,
                              width: 1441.0,
                              height: 1.0,
                              child: GeneratedLine19Widget10(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 616.0,
                              right: null,
                              bottom: null,
                              width: 1441.0,
                              height: 1.0,
                              child: GeneratedLine20Widget10(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 253.0,
                              height: 138.0,
                              child: GeneratedImage2Widget1(),
                            ),
                            Positioned(
                              left: 498.0,
                              top: 244.0,
                              right: null,
                              bottom: null,
                              width: 528.0,
                              height: 52.0,
                              child: GeneratedBCABANKINGWidget1(),
                            ),
                            Positioned(
                              left: 1191.0,
                              top: 188.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 162.0,
                              child: GeneratedEllipse12Widget(),
                            ),
                            Positioned(
                              left: 1191.0,
                              top: 417.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 162.0,
                              child: GeneratedEllipse13Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.07491731113857693;

                                final double height =
                                    constraints.maxHeight * 0.0791015625;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.8465277777777778,
                                      y: constraints.maxHeight * 0.2265625,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratediconcheckmarkoutlineWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.07491731113857693;

                                final double height =
                                    constraints.maxHeight * 0.0791015625;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.8465277777777778,
                                      y: constraints.maxHeight * 0.447265625,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratediconcheckmarkoutlineWidget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.14375;

                                final double height =
                                    constraints.maxHeight * 0.2021484375;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.04375,
                                      y: constraints.maxHeight * 0.3681640625,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratediconcameraoutlineWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 534.0,
                              top: 427.0,
                              right: null,
                              bottom: null,
                              width: 456.0,
                              height: 146.0,
                              child: GeneratedCODpayonthespotWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
