import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox62widget/generated/GeneratedRectangle86Widget16.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox62widget/generated/GeneratedMybasketWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox62widget/generated/GeneratediconarrowbackoutlineWidget37.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox62widget/generated/GeneratedGroup27Widget14.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox62widget/generated/GeneratedPSGWidget12.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox62widget/generated/GeneratedThisPSGjerseyhasanelegantpurplishbluecolordominanceWidg1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox62widget/generated/GeneratedBuynowWidget38.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox62widget/generated/GeneratedRectangle196Widget27.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox62widget/generated/GeneratedRp155000Widget21.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame iPhone 11 Pro / X - 62
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX62Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 98.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 82.0,
                child: GeneratedMybasketWidget4(),
              ),
              Positioned(
                left: 12.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 100.0,
                child: GeneratedGroup27Widget14(),
              ),
              Positioned(
                left: 119.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 31.0,
                child: GeneratedPSGWidget12(),
              ),
              Positioned(
                left: 119.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 205.0,
                height: 50.0,
                child:
                    GeneratedThisPSGjerseyhasanelegantpurplishbluecolordominanceWidg1(),
              ),
              Positioned(
                left: 255.0,
                top: 165.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 14.0,
                child: GeneratedRp155000Widget21(),
              ),
              Positioned(
                left: 267.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 49.0,
                child: GeneratedRectangle196Widget27(),
              ),
              Positioned(
                left: 276.0,
                top: 771.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 57.0,
                child: GeneratedBuynowWidget38(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.005333333333333333,
                        y: constraints.maxHeight * -0.008620689655172414,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget37(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 35.0,
                top: 156.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 88.0,
                child: GeneratedRectangle86Widget16(),
              )
            ]),
      ),
    ));
  }
}
