import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedTotalpaymentRp155000Widget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedBARCELONAFCWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedGroup22Widget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedRectangle132Widget20.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedRectangle121Widget29.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedRectangle131Widget17.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedRectangle130Widget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedRectangle122Widget26.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedImage1Widget34.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedName62JlWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedShippingaddressWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedPaymentconfirmationWidget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox65widget/generated/GeneratedRectangle81Widget19.dart';

/* Frame iPhone 11 Pro / X - 65
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX65Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 231.0,
                child: GeneratedRectangle121Widget29(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 78.0,
                child: GeneratedRectangle122Widget26(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 116.0,
                child: GeneratedImage1Widget34(),
              ),
              Positioned(
                left: 99.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 118.0,
                child: GeneratedShippingaddressWidget3(),
              ),
              Positioned(
                left: 50.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 114.0,
                child: GeneratedName62JlWidget3(),
              ),
              Positioned(
                left: 38.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 58.0,
                child: GeneratedBARCELONAFCWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 741.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 75.0,
                child: GeneratedGroup22Widget11(),
              ),
              Positioned(
                left: 181.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 70.0,
                child: GeneratedRectangle130Widget15(),
              ),
              Positioned(
                left: 99.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 72.0,
                child: GeneratedTotalpaymentRp155000Widget10(),
              ),
              Positioned(
                left: 268.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 53.0,
                child: GeneratedRectangle131Widget17(),
              ),
              Positioned(
                left: 268.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 53.0,
                child: GeneratedRectangle132Widget20(),
              ),
              Positioned(
                left: 257.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 91.0,
                child: GeneratedPaymentconfirmationWidget10(),
              ),
              Positioned(
                left: 90.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 260.0,
                child: GeneratedRectangle81Widget19(),
              )
            ]),
      ),
    ));
  }
}
