import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedNameWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedRectangle161Widget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedWidget22.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedRectangle160Widget14.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedRectangle158Widget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedLine7Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedWidget24.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedRectangle162Widget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratediconarrowbackoutlineWidget45.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedUbahWidget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedAddressWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedRectangle157Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedWidget23.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedGenderWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedRectangle159Widget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedChangeProfileWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox77widget/generated/GeneratedConfirmWidget7.dart';

/* Frame iPhone 11 Pro / X - 77
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX77Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 213.0,
                child: GeneratedRectangle157Widget6(),
              ),
              Positioned(
                left: 77.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 78.0,
                child: GeneratedChangeProfileWidget4(),
              ),
              Positioned(
                left: 165.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: GeneratedRectangle158Widget15(),
              ),
              Positioned(
                left: 162.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 12.0,
                child: GeneratedUbahWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 52.0,
                child: GeneratedRectangle159Widget15(),
              ),
              Positioned(
                left: 0.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 50.0,
                child: GeneratedRectangle160Widget14(),
              ),
              Positioned(
                left: 0.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine7Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 54.0,
                child: GeneratedNameWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 54.0,
                child: GeneratedGenderWidget4(),
              ),
              Positioned(
                left: 263.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 55.0,
                child: GeneratedWidget22(),
              ),
              Positioned(
                left: 263.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 55.0,
                child: GeneratedWidget23(),
              ),
              Positioned(
                left: 0.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 52.0,
                child: GeneratedRectangle161Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 54.0,
                child: GeneratedAddressWidget4(),
              ),
              Positioned(
                left: 263.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 55.0,
                child: GeneratedWidget24(),
              ),
              Positioned(
                left: 262.0,
                top: 758.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 54.0,
                child: GeneratedRectangle162Widget9(),
              ),
              Positioned(
                left: 256.0,
                top: 754.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 66.0,
                child: GeneratedConfirmWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.010666666666666666,
                        y: constraints.maxHeight * -0.008620689655172414,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget45(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
