import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedRectangle195Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedKomentarWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedLine27Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedIlhamUdinWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedLine32Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedRectangle153Widget19.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedLine29Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedRectangle150Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedRectangle152Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedLine28Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedLine31Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedRectangle174Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedRectangle194Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedRectangle155Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedRectangle151Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedRectangle149Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedRectangle154Widget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedKomentarWidget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedLine45Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedLine30Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedLine46Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedRectangle193Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedAchmadAlifWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget/generated/GeneratedRiskySaputraWidget.dart';

/* Frame iPhone 11 Pro / X - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 33.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 88.81967163085938,
                height: 86.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 83.10111999511719,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 86.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 84.89994049072266,
                height: 1.0,
                child: GeneratedLine27Widget(),
              ),
              Positioned(
                left: 108.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 89.8276138305664,
                height: 1.0,
                child: GeneratedLine28Widget7(),
              ),
              Positioned(
                left: 47.0,
                top: 399.0,
                right: null,
                bottom: null,
                width: 82.2192153930664,
                height: 1.0,
                child: GeneratedLine29Widget7(),
              ),
              Positioned(
                left: 107.0,
                top: 399.0,
                right: null,
                bottom: null,
                width: 84.89994049072266,
                height: 1.0,
                child: GeneratedLine30Widget7(),
              ),
              Positioned(
                left: 49.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 86.4522933959961,
                height: 1.0,
                child: GeneratedLine31Widget7(),
              ),
              Positioned(
                left: 110.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 86.31338500976562,
                height: 1.0,
                child: GeneratedLine32Widget(),
              ),
              Positioned(
                left: 51.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 78.0,
                child: GeneratedKomentarWidget(),
              ),
              Positioned(
                left: 139.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 26.0,
                child: GeneratedRectangle149Widget2(),
              ),
              Positioned(
                left: 139.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 26.0,
                child: GeneratedRiskySaputraWidget(),
              ),
              Positioned(
                left: 139.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 26.0,
                child: GeneratedRectangle150Widget2(),
              ),
              Positioned(
                left: 142.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 199.0,
                height: 28.0,
                child: GeneratedIlhamUdinWidget2(),
              ),
              Positioned(
                left: 139.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 26.0,
                child: GeneratedRectangle151Widget(),
              ),
              Positioned(
                left: 138.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 29.0,
                child: GeneratedAchmadAlifWidget2(),
              ),
              Positioned(
                left: 139.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 78.0,
                child: GeneratedRectangle152Widget2(),
              ),
              Positioned(
                left: 139.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 78.0,
                child: GeneratedRectangle153Widget19(),
              ),
              Positioned(
                left: 139.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 78.0,
                child: GeneratedRectangle154Widget1(),
              ),
              Positioned(
                left: 82.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 67.0,
                child: GeneratedRectangle155Widget(),
              ),
              Positioned(
                left: 51.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 78.0,
                child: GeneratedKomentarWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 50.0,
                child: GeneratedRectangle174Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 82.00609588623047,
                height: 1.0,
                child: GeneratedLine45Widget7(),
              ),
              Positioned(
                left: 64.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 81.21575927734375,
                height: 1.0,
                child: GeneratedLine46Widget8(),
              ),
              Positioned(
                left: 28.0,
                top: 753.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 58.0,
                child: GeneratedRectangle193Widget2(),
              ),
              Positioned(
                left: 29.0,
                top: 752.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 60.0,
                child: GeneratedRectangle194Widget2(),
              ),
              Positioned(
                left: 291.0,
                top: 754.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 58.0,
                child: GeneratedRectangle195Widget2(),
              ),
              Positioned(
                left: 78.0,
                top: 767.0,
                right: null,
                bottom: null,
                width: 218.0,
                height: 66.0,
                child: GeneratedWidget3(),
              )
            ]),
      ),
    ));
  }
}
