import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget/generated/GeneratedRectangle103Widget12.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget/generated/GeneratedRectangle114Widget11.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget/generated/GeneratediconarrowbackoutlineWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget/generated/GeneratedRectangle78Widget33.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget/generated/GeneratedRectangle115Widget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget/generated/GeneratedRectangle102Widget20.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget/generated/GeneratedBuyNowWidget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget/generated/GeneratedRectangle113Widget37.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget/generated/GeneratedLetstakeyourjersethomeWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget/generated/GeneratedGroup12Widget23.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame iPhone 11 Pro / X - 34
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX34Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 28.0,
                top: 420.9999084472656,
                right: null,
                bottom: null,
                width: 320.0,
                height: 120.0,
                child: GeneratedGroup12Widget23(),
              ),
              Positioned(
                left: 150.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedRectangle113Widget37(),
              ),
              Positioned(
                left: 225.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedRectangle114Widget11(),
              ),
              Positioned(
                left: 150.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedRectangle103Widget12(),
              ),
              Positioned(
                left: 300.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedRectangle115Widget13(),
              ),
              Positioned(
                left: 225.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedRectangle102Widget20(),
              ),
              Positioned(
                left: 294.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 77.0,
                child: GeneratedBuyNowWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 752.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 77.0,
                child: GeneratedLetstakeyourjersethomeWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 330.0,
                child: GeneratedRectangle78Widget33(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.018666666666666668,
                        y: constraints.maxHeight * -0.012315270935960592,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
