import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup38widget3/generated/GeneratedGroup28Widget16.dart';

/* Group Group 38
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup38Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 378.0,
      height: 842.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(0.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 378.0,
              height: 842.0,
              child: GeneratedGroup28Widget16(),
            )
          ]),
    ));
  }
}
