import 'package:flutter/material.dart';

/* Text Lets take your jersey home!!!
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLetstakeyourjerseyhomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Lets take your jersey home!!!''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 70.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
