import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget1/generated/GeneratedGroup10Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget1/generated/GeneratedGroup11Widget15.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget1/generated/GeneratedSendRatingWidget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox11widget1/generated/GeneratedThankyouLadsWidget7.dart';

/* Frame iPhone 11 Pro / X - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX11Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 65.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 145.0,
                child: GeneratedThankyouLadsWidget7(),
              ),
              Positioned(
                left: 39.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 76.0,
                child: GeneratedGroup10Widget5(),
              ),
              Positioned(
                left: 39.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 75.09091186523438,
                child: GeneratedGroup11Widget15(),
              ),
              Positioned(
                left: 37.0,
                top: 507.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 81.0,
                child: GeneratedSendRatingWidget5(),
              )
            ]),
      ),
    ));
  }
}
