import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedPasswordWidget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedArrowright113Widget36.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedRectangle77Widget20.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedLine71Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedRectangle199Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedRectangle202Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedRectangle198Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedLine72Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedEmailWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedTennisball1Widget20.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedSigninWidget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedRectangle203Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediminnwidget20/generated/GeneratedLoginWidget8.dart';

/* Frame IMINN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIMINNWidget20 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1080.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 1080.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 690.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedTennisball1Widget20(),
                            ),
                            Positioned(
                              left: 1849.0,
                              top: 174.0,
                              right: null,
                              bottom: null,
                              width: 13.0,
                              height: 13.0,
                              child: GeneratedArrowright113Widget36(),
                            ),
                            Positioned(
                              left: 669.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 283.0,
                              child: GeneratedRectangle77Widget20(),
                            ),
                            Positioned(
                              left: 809.0,
                              top: 101.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 128.0,
                              child: GeneratedLoginWidget8(),
                            ),
                            Positioned(
                              left: 582.0,
                              top: 471.0,
                              right: null,
                              bottom: null,
                              width: 759.0,
                              height: 141.0,
                              child: GeneratedRectangle198Widget7(),
                            ),
                            Positioned(
                              left: 582.0,
                              top: 613.0,
                              right: null,
                              bottom: null,
                              width: 759.0,
                              height: 141.0,
                              child: GeneratedRectangle199Widget7(),
                            ),
                            Positioned(
                              left: 343.0,
                              top: 471.0,
                              right: null,
                              bottom: null,
                              width: 773.0,
                              height: 147.0,
                              child: GeneratedEmailWidget4(),
                            ),
                            Positioned(
                              left: 415.0,
                              top: 633.0,
                              right: null,
                              bottom: null,
                              width: 755.0,
                              height: 140.0,
                              child: GeneratedPasswordWidget10(),
                            ),
                            Positioned(
                              left: 870.0,
                              top: 239.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 181.0,
                              child: GeneratedRectangle202Widget6(),
                            ),
                            Positioned(
                              left: 870.0,
                              top: 239.0,
                              right: null,
                              bottom: null,
                              width: 255.2665252685547,
                              height: 1.0,
                              child: GeneratedLine71Widget2(),
                            ),
                            Positioned(
                              left: 1050.0,
                              top: 239.0,
                              right: null,
                              bottom: null,
                              width: 255.26654052734375,
                              height: 1.0,
                              child: GeneratedLine72Widget2(),
                            ),
                            Positioned(
                              left: 552.0,
                              top: 780.0,
                              right: null,
                              bottom: null,
                              width: 813.0,
                              height: 133.0,
                              child: GeneratedRectangle203Widget6(),
                            ),
                            Positioned(
                              left: 549.0,
                              top: 780.0,
                              right: null,
                              bottom: null,
                              width: 818.0,
                              height: 126.0,
                              child: GeneratedSigninWidget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
