import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget3/generated/GeneratedLine44Widget22.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget3/generated/GeneratedOkeWidget22.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget3/generated/GeneratedRectangle137Widget27.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget3/generated/GeneratedLine43Widget22.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget3/generated/GeneratedEllipse4Widget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget3/generated/GeneratedSelamatpembayaranandasudahberhasilWidget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget3/generated/GeneratedRectangle136Widget9.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox14widget3/generated/GeneratedLogoutWidget19.dart';

/* Frame iPhone 11 Pro / X - 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX14Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 65.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 138.0,
                child: GeneratedSelamatpembayaranandasudahberhasilWidget7(),
              ),
              Positioned(
                left: 62.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 80.0,
                child: GeneratedRectangle136Widget9(),
              ),
              Positioned(
                left: 83.0,
                top: 507.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 62.0,
                child: GeneratedOkeWidget22(),
              ),
              Positioned(
                left: 193.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 83.0,
                child: GeneratedRectangle137Widget27(),
              ),
              Positioned(
                left: 169.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 65.0,
                child: GeneratedLogoutWidget19(),
              ),
              Positioned(
                left: 87.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 192.0,
                child: GeneratedEllipse4Widget6(),
              ),
              Positioned(
                left: 114.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 206.63494873046875,
                height: 1.0,
                child: GeneratedLine43Widget22(),
              ),
              Positioned(
                left: 277.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 211.0094757080078,
                height: 1.0,
                child: GeneratedLine44Widget22(),
              )
            ]),
      ),
    ));
  }
}
