import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop59widget/generated/GeneratedGroup46Widget5.dart';

/* Frame Desktop - 59
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop59Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 198.0,
                              right: null,
                              bottom: null,
                              width: 1040.0,
                              height: 639.8629760742188,
                              child: GeneratedGroup46Widget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
