import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox19widget2/generated/GeneratedVectorWidget531.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox19widget2/generated/GeneratedLetstakeyourjersethomeWidget6.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox19widget2/generated/GeneratediconarrowbackoutlineWidget25.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox19widget2/generated/GeneratedRectangle88Widget17.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox19widget2/generated/GeneratedGroup46Widget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox19widget2/generated/GeneratedRectangle229Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox19widget2/generated/GeneratediconshoppingcartWidget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox19widget2/generated/GeneratedRectangle228Widget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox19widget2/generated/GeneratedGroup12Widget36.dart';

/* Frame iPhone 11 Pro / X - 19
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX19Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 28.0,
                top: 420.9999084472656,
                right: null,
                bottom: null,
                width: 320.0,
                height: 120.0,
                child: GeneratedGroup12Widget36(),
              ),
              Positioned(
                left: 79.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 239.0,
                height: 330.0,
                child: GeneratedRectangle88Widget17(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.018666666666666668,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget25(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 65.0,
                child: GeneratedRectangle228Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 65.0,
                child: GeneratedRectangle229Widget8(),
              ),
              Positioned(
                left: 8.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 77.0,
                child: GeneratedLetstakeyourjersethomeWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.1473709716796875;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 55.26411437988281;

                  double percentHeight = 0.06486867331518915;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      52.673362731933594;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.4266666666666667,
                        translateY: constraints.maxHeight * 0.9285714285714286,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget531())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.25066666666666665;

                  final double height =
                      constraints.maxHeight * 0.08251231527093596;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6053333333333333,
                        y: constraints.maxHeight * 0.9174876847290641,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconshoppingcartWidget10(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 285.0,
                top: 752.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 58.0,
                child: GeneratedGroup46Widget6(),
              )
            ]),
      ),
    ));
  }
}
