import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatedgroup46widget8/generated/GeneratedGroup32Widget10.dart';

/* Group Group 46
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup46Widget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 812.0,
              child: GeneratedGroup32Widget10(),
            )
          ]),
    ));
  }
}
