import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedRectangle154Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedLine22Widget3.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedEllipse2Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratediconarrowbackoutlineWidget20.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedRectangle195Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedIlhamUdinWidget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedEllipse3Widget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedRiskySaputraWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedWidget20.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedAchmadAlifWidget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedCommentWidget.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedRectangle150Widget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedRectangle149Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedRectangle194Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedRectangle153Widget42.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedRectangle193Widget8.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedRectangle151Widget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedRectangle152Widget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox10widget2/generated/GeneratedEllipse1Widget5.dart';

/* Frame iPhone 11 Pro / X - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX10Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 33.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 88.81967163085938,
                height: 86.0,
                child: GeneratedEllipse1Widget5(),
              ),
              Positioned(
                left: 33.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 83.10111999511719,
                child: GeneratedEllipse2Widget2(),
              ),
              Positioned(
                left: 33.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 86.0,
                child: GeneratedEllipse3Widget2(),
              ),
              Positioned(
                left: 70.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 78.0,
                child: GeneratedCommentWidget(),
              ),
              Positioned(
                left: 139.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 26.0,
                child: GeneratedRectangle149Widget8(),
              ),
              Positioned(
                left: 139.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 26.0,
                child: GeneratedRectangle150Widget10(),
              ),
              Positioned(
                left: 139.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 26.0,
                child: GeneratedRectangle151Widget4(),
              ),
              Positioned(
                left: 139.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 78.0,
                child: GeneratedRectangle152Widget10(),
              ),
              Positioned(
                left: 139.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 78.0,
                child: GeneratedRectangle153Widget42(),
              ),
              Positioned(
                left: 139.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 78.0,
                child: GeneratedRectangle154Widget7(),
              ),
              Positioned(
                left: 139.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 26.0,
                child: GeneratedRiskySaputraWidget2(),
              ),
              Positioned(
                left: 142.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 199.0,
                height: 28.0,
                child: GeneratedIlhamUdinWidget8(),
              ),
              Positioned(
                left: 138.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 29.0,
                child: GeneratedAchmadAlifWidget8(),
              ),
              Positioned(
                left: 28.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 58.0,
                child: GeneratedRectangle193Widget8(),
              ),
              Positioned(
                left: 300.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 58.0,
                child: GeneratedRectangle195Widget8(),
              ),
              Positioned(
                left: 28.0,
                top: 747.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 60.0,
                child: GeneratedRectangle194Widget8(),
              ),
              Positioned(
                left: 78.0,
                top: 751.0,
                right: null,
                bottom: null,
                width: 239.0,
                height: 66.0,
                child: GeneratedWidget20(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.013333333333333334,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget20(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine22Widget3(),
              )
            ]),
      ),
    ));
  }
}
