import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox23widget1/generated/GeneratedKeranjangsayaWidget4.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox23widget1/generated/GeneratedMANCHESTERUNITEDWidget10.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox23widget1/generated/GeneratedRectangle196Widget17.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox23widget1/generated/GeneratedJerseymanchesterunitedinimemilikidominasiwarnamerahdeng1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox23widget1/generated/GeneratedRp155000Widget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox23widget1/generated/GeneratedBelisekarangWidget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox23widget1/generated/GeneratedGroup27Widget7.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox23widget1/generated/GeneratediconarrowbackoutlineWidget8.dart';

/* Frame iPhone 11 Pro / X - 23
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX23Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 77.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 82.0,
                child: GeneratedKeranjangsayaWidget4(),
              ),
              Positioned(
                left: 12.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 100.0,
                child: GeneratedGroup27Widget7(),
              ),
              Positioned(
                left: 118.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 28.0,
                child: GeneratedMANCHESTERUNITEDWidget10(),
              ),
              Positioned(
                left: 119.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 50.0,
                child:
                    GeneratedJerseymanchesterunitedinimemilikidominasiwarnamerahdeng1(),
              ),
              Positioned(
                left: 308.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 14.0,
                child: GeneratedRp155000Widget8(),
              ),
              Positioned(
                left: 267.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 49.0,
                child: GeneratedRectangle196Widget17(),
              ),
              Positioned(
                left: 267.0,
                top: 768.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 54.0,
                child: GeneratedBelisekarangWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.216;

                  final double height =
                      constraints.maxHeight * 0.07635467980295567;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.010666666666666666,
                        y: constraints.maxHeight * -0.007389162561576354,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget8(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
