import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop62widget/generated/GeneratedRectangle216Widget5.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop62widget/generated/GeneratedGroup41Widget21.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generateddesktop62widget/generated/GeneratedChooseWidget2.dart';

/* Frame Desktop - 62
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop62Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1029.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1439.9996337890625,
                              height: 907.999755859375,
                              child: GeneratedGroup41Widget21(),
                            ),
                            Positioned(
                              left: 1275.0,
                              top: 957.0,
                              right: null,
                              bottom: null,
                              width: 165.0,
                              height: 67.0,
                              child: GeneratedRectangle216Widget5(),
                            ),
                            Positioned(
                              left: 1275.0,
                              top: 956.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 73.0,
                              child: GeneratedChooseWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
