import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget1/generated/GeneratedAreyousureyouareloggedoutasaguestWidget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget1/generated/GeneratedRectangle139Widget12.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget1/generated/GeneratedCancelWidget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget1/generated/GeneratedRectangle138Widget18.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox34widget1/generated/GeneratedGetoutWidget.dart';

/* Frame iPhone 11 Pro / X - 34
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX34Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 43.0,
                top: 165.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 96.0,
                child: GeneratedAreyousureyouareloggedoutasaguestWidget1(),
              ),
              Positioned(
                left: 69.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 56.0,
                child: GeneratedRectangle138Widget18(),
              ),
              Positioned(
                left: 52.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 53.0,
                child: GeneratedCancelWidget1(),
              ),
              Positioned(
                left: 200.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 56.0,
                child: GeneratedRectangle139Widget12(),
              ),
              Positioned(
                left: 192.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 35.0,
                child: GeneratedGetoutWidget(),
              )
            ]),
      ),
    ));
  }
}
