import 'package:flutter/material.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox39widget/generated/GeneratedAreyousureyouareloggedoutasauserWidget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox39widget/generated/GeneratedCancelWidget2.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox39widget/generated/GeneratedGetoutWidget1.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox39widget/generated/GeneratedRectangle139Widget13.dart';
import 'package:flutterapp/penjualan_20jerseyapp/generatediphone11prox39widget/generated/GeneratedRectangle138Widget19.dart';

/* Frame iPhone 11 Pro / X - 39
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX39Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 14.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 166.0,
                child: GeneratedAreyousureyouareloggedoutasauserWidget1(),
              ),
              Positioned(
                left: 38.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 59.0,
                child: GeneratedRectangle138Widget19(),
              ),
              Positioned(
                left: 44.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 53.0,
                child: GeneratedCancelWidget2(),
              ),
              Positioned(
                left: 184.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 59.0,
                child: GeneratedRectangle139Widget13(),
              ),
              Positioned(
                left: 189.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 29.0,
                child: GeneratedGetoutWidget1(),
              )
            ]),
      ),
    ));
  }
}
